import type { ArtisticInfluence } from '../types';

export const ARTISTIC_INFLUENCES: ArtisticInfluence[] = [
  // --- Master Painters ---
  { id: 1, name: 'Vincent van Gogh', knownFor: 'Expressive, impasto brushwork and bold, emotional color palettes.' },
  { id: 2, name: 'Leonardo da Vinci', knownFor: 'Masterful realism, soft sfumato shading, and deep anatomical understanding.' },
  { id: 3, name: 'Salvador Dalí', knownFor: 'Bizarre, dreamlike scenes and meticulously rendered surrealist imagery.' },
  { id: 4, name: 'Pablo Picasso', knownFor: 'Pioneering Cubism, deconstructing subjects into geometric forms.' },
  { id: 5, name: 'Frida Kahlo', knownFor: 'Striking, deeply personal self-portraits blending realism with surrealist and folk art elements.' },
  { id: 6, name: 'Rembrandt van Rijn', knownFor: 'Dramatic use of light and shadow (chiaroscuro) and raw, honest portraiture.' },
  { id: 7, name: 'Claude Monet', knownFor: 'Founder of Impressionism, capturing fleeting moments with visible brushstrokes and a focus on light.' },
  { id: 8, name: 'Caravaggio', knownFor: 'Intense, dramatic tenebrism with dark backgrounds and theatrical lighting.' },
  { id: 35, name: 'Hieronymus Bosch', knownFor: 'Fantastical, hellish landscapes filled with bizarre creatures and complex narratives.' },
  { id: 36, name: 'Gustav Klimt', knownFor: 'Elegant, decorative style, opulent gold leaf, and sensual subject matter of the Vienna Secession.' },
  { id: 37, name: 'Francis Bacon', knownFor: 'Raw, emotionally charged, and grotesque figurative paintings with a sense of motion.' },
  { id: 38, name: 'J.M.W. Turner', knownFor: 'Romantic and expressive landscapes, masterful in capturing light, weather, and the sublime.' },
  { id: 39, name: 'Edvard Munch', knownFor: 'Intensely evocative, psychological paintings dealing with themes of anxiety, love, and death, like "The Scream".' },
  { id: 40, name: 'Georgia O\'Keeffe', knownFor: 'American modernist known for her large-scale paintings of flowers, skyscrapers, and New Mexico landscapes.' },
  { id: 41, name: 'Andy Warhol', knownFor: 'Leading figure in Pop Art, exploring celebrity culture and advertising with screenprinting techniques.' },
  { id: 42, name: 'Roy Lichtenstein', knownFor: 'Pop artist famous for his comic book-inspired paintings using Ben-Day dots.' },
  { id: 43, name: 'Mark Rothko', knownFor: 'Abstract Expressionist known for his large color field paintings with luminous, floating rectangles.' },
  { id: 44, name: 'Jackson Pollock', knownFor: 'Pioneering Abstract Expressionism with his iconic drip and action painting techniques.' },
  { id: 45, name: 'Wassily Kandinsky', knownFor: 'A pioneer of abstract art, using color and form to create a spiritual and emotional response.' },
  { id: 46, name: 'Piet Mondrian', knownFor: 'De Stijl artist known for his abstract grid paintings using primary colors, black, and white.' },
  { id: 47, name: 'Egon Schiele', knownFor: 'Austrian Expressionist known for his raw, twisted, and psychologically intense figurative works.' },
  
  // --- Graffiti & Street Artists ---
  { id: 9, name: 'Jean-Michel Basquiat', knownFor: 'A raw, neo-expressionist style mixing graffiti, text, and abstract figures with intense energy.' },
  { id: 10, name: 'Banksy', knownFor: 'Iconic, satirical stencil art with sharp political and social commentary.' },
  { id: 11, name: 'Keith Haring', knownFor: 'Dynamic, bold-lined figures and vibrant, pop-art graffiti style.' },
  { id: 12, name: 'Shepard Fairey (Obey)', knownFor: 'A graphic, propaganda poster style using stylized imagery and bold typography.' },
  { id: 13, name: 'KAWS', knownFor: 'Pop art characters with signature "X" eyes, bridging street art, toys, and fashion.' },
  { id: 48, name: 'Futura 2000', knownFor: 'A pioneer of abstract graffiti, using thin, clean spray lines and sci-fi imagery.' },
  { id: 49, name: 'Dondi White', knownFor: 'A graffiti legend known for his complex, stylish, and influential lettering on NYC subway trains.' },
  { id: 50, name: 'Lady Pink', knownFor: 'A pioneering female graffiti artist, known for her bold murals and classic bubble letters.' },
  { id: 51, name: 'Invader', knownFor: 'Creating pixelated mosaic tile art inspired by 8-bit video games, placed in cities worldwide.' },
  { id: 52, name: 'Vhils', knownFor: 'Creating large-scale portraits by carving, drilling, and blasting away layers of walls.' },

  // --- Comic Book & Graphic Novel Artists ---
  { id: 14, name: 'Jack Kirby', knownFor: 'The "King of Comics," with dynamic, explosive action, powerful figures, and "Kirby Krackle" energy effects.' },
  { id: 15, name: 'Mike Mignola', knownFor: 'Creator of Hellboy, using heavy shadows, stark contrasts, and a gothic, minimalist style.' },
  { id: 16, name: 'Jim Lee', knownFor: 'A highly detailed, cross-hatched, and dynamic superhero style that defined 90s comics.' },
  { id: 17, name: 'Moebius (Jean Giraud)', knownFor: 'Masterful, clean linework and imaginative, surreal sci-fi and fantasy worlds.' },
  { id: 18, name: 'Frank Miller', knownFor: 'A gritty, noir-inspired, high-contrast style, famous for "The Dark Knight Returns" and "Sin City".' },
  { id: 19, name: 'Todd McFarlane', knownFor: 'An exaggerated, highly detailed style with "spaghetti webbing", defining Spawn and his work on Spider-Man.' },
  { id: 20, name: 'Bill Sienkiewicz', knownFor: 'An experimental, mixed-media approach incorporating painting, collage, and abstract forms into comics.' },
  { id: 21, name: 'Geof Darrow', knownFor: 'Incredibly intricate, hyper-detailed linework with a chaotic sense of action and scale.' },
  { id: 53, name: 'Jhonen Vasquez', knownFor: 'The creator of "Invader Zim", with a spidery, gothic, and darkly satirical comic art style.' },
  { id: 54, name: 'Will Eisner', knownFor: 'A master of sequential art, known for "The Spirit" and popularizing the term "graphic novel".' },
  { id: 55, name: 'Steve Ditko', knownFor: 'Co-creator of Spider-Man and Doctor Strange, with a quirky, expressive, and slightly surreal style.' },
  { id: 56, name: 'Frank Frazetta', knownFor: 'Legendary fantasy painter known for his powerful, dynamic, and visceral illustrations of heroes and monsters.' },
  { id: 57, name: 'Robert Crumb', knownFor: 'A key figure in underground comix, with a distinctive, cross-hatched, and often satirical style.' },
  { id: 58, name: 'Alex Ross', knownFor: 'A photorealistic, painted comic book style that brings superheroes to life with classical grandeur.' },
  { id: 59, name: 'Chris Ware', knownFor: 'A formalist approach to comics with complex layouts, clean lines, and melancholic storytelling.' },
  { id: 60, name: 'Daniel Clowes', knownFor: 'Indie comic creator ("Ghost World") with a clean, precise style and character-focused stories.' },
  { id: 61, name: 'Jamie Hewlett', knownFor: 'The artist behind Gorillaz and "Tank Girl", with a chaotic, punk-rock, and stylish aesthetic.' },
  { id: 62, name: 'Charles Burns', knownFor: 'Known for "Black Hole," with a creepy, high-contrast, and precise style that evokes body horror.' },
  { id: 63, name: 'Dave McKean', knownFor: 'A mixed-media artist known for his work on "Sandman" covers, using collage, photography, and painting.' },

  // --- Manga & Anime Artists/Directors ---
  { id: 22, name: 'Hayao Miyazaki', knownFor: 'Lush, enchanting, and detailed animation direction with a focus on nature, flight, and whimsical characters (Studio Ghibli).' },
  { id: 23, name: 'Katsuhiro Otomo', knownFor: 'Hyper-detailed, realistic cyberpunk aesthetic with a cinematic scope, creator of "Akira".' },
  { id: 24, name: 'Junji Ito', knownFor: 'Master of horror manga, known for grotesque body horror and terrifying, unsettling concepts.' },
  { id: 25, name: 'Akira Toriyama', knownFor: 'The iconic, dynamic, and clean art style of "Dragon Ball," defining shōnen manga for generations.' },
  { id: 26, name: 'Kentaro Miura', knownFor: 'The incredibly detailed, dark, and epic fantasy style of the manga "Berserk".' },
  { id: 27, name: 'Satoshi Kon', knownFor: 'Surreal and psychological anime direction, blending dreams and reality in films like "Paprika" and "Perfect Blue".' },
  { id: 64, name: 'Osamu Tezuka', knownFor: 'The "Godfather of Manga," with a pioneering, expressive, and cinematic cartoon style ("Astro Boy").' },
  { id: 65, name: 'Masamune Shirow', knownFor: 'Creator of "Ghost in the Shell," known for intricate detail in technology and cyberpunk settings.' },
  { id: 66, name: 'Rumiko Takahashi', knownFor: 'A versatile and highly influential manga artist with a clean, expressive, and comedic style ("Inuyasha", "Ranma 1/2").' },
  { id: 67, name: 'CLAMP', knownFor: 'A collective of female artists with an elegant, detailed, and often elaborate shōjo and fantasy style.' },
  { id: 68, name: 'Takehiko Inoue', knownFor: 'Known for "Slam Dunk" and "Vagabond," with a realistic, fluid style and masterful ink brushwork.' },
  { id: 69, name: 'Naoko Takeuchi', knownFor: 'The creator of "Sailor Moon," with a graceful, fashionable, and iconic magical girl art style.' },
  { id: 70, name: 'Hirohiko Araki', knownFor: 'The creator of "JoJo\'s Bizarre Adventure," known for its unique, evolving art style, dynamic poses, and high-fashion influences.' },
  { id: 71, name: 'Eiichiro Oda', knownFor: 'The creator of "One Piece," with a distinctive, rubbery, and incredibly imaginative cartoon style.' },
  
  // --- Illustrators, Designers & Other Styles ---
  { id: 28, name: 'H.R. Giger', knownFor: 'The creator of the Xenomorph from "Alien," known for his dark, biomechanical surrealism.' },
  { id: 29, name: 'Alphonse Mucha', knownFor: 'The definitive Art Nouveau style, with ornate, flowing lines, decorative patterns, and elegant figures.' },
  { id: 30, name: 'James Jean', knownFor: 'Intricate, psychedelic, and flowing compositions that blend Eastern and Western art traditions.' },
  { id: 31, name: 'Zdzisław Beksiński', knownFor: 'Dystopian surrealism, painting grim, post-apocalyptic landscapes and haunting figures.' },
  { id: 32, name: 'Yoshitaka Amano', knownFor: 'Delicate, ethereal, and intricate ink and watercolor illustrations, famous for his "Final Fantasy" concept art.' },
  { id: 33, name: 'Tim Burton', knownFor: 'A distinct gothic, whimsical, and quirky style with stylized characters and dark, fairy-tale aesthetics.' },
  { id: 34, name: 'Chuck Jones', knownFor: 'Master animator behind Looney Tunes, known for expressive character animation and comedic timing.' },
  { id: 72, name: 'Jeff Gaither', knownFor: 'The illustrator for Insane Clown Posse, with a distinctive airbrushed, horrorcore aesthetic.' },
  { id: 73, name: 'Drew Struzan', knownFor: 'Legendary movie poster artist with a realistic, painted style that defined a generation of film art.' },
  { id: 74, name: 'Syd Mead', knownFor: 'A "visual futurist" and concept artist known for his sleek, detailed designs for films like "Blade Runner" and "Tron".' },
  { id: 75, name: 'Ralph McQuarrie', knownFor: 'The legendary concept artist whose paintings defined the look and feel of the original "Star Wars" trilogy.' },
  { id: 76, name: 'M.C. Escher', knownFor: 'Creating mathematically inspired woodcuts and lithographs featuring impossible constructions and tessellations.' },
  { id: 77, name: 'Norman Rockwell', knownFor: 'Iconic American painter and illustrator, capturing idealized scenes of everyday life with narrative detail.' },
  { id: 78, name: 'Maxfield Parrish', knownFor: 'Luminous, idealized neoclassical paintings with a signature "Parrish blue" color.' },
  { id: 79, name: 'Aubrey Beardsley', knownFor: 'An English illustrator known for his dark, grotesque, and elegant black ink drawings in the Art Nouveau style.' },
  { id: 80, name: 'Edward Gorey', knownFor: 'Gothic and humorous pen-and-ink illustrations of Victorian and Edwardian settings with a sense of macabre.' },
  { id: 81, name: 'Brian Froud', knownFor: 'Fantasy illustrator and conceptual designer for films like "The Dark Crystal" and "Labyrinth", known for his faeries and goblins.' },

  // --- Photographers ---
  { id: 82, name: 'Tom Wood', knownFor: 'Candid and intimate street photography, capturing the raw, unposed culture of Liverpool.' },
  { id: 83, name: 'Ansel Adams', knownFor: 'Master of landscape photography, known for his black-and-white images of the American West.' },
  { id: 84, name: 'Annie Leibovitz', knownFor: 'Iconic and intimate celebrity portraits, often with elaborate staging and concepts.' },
  { id: 85, name: 'Henri Cartier-Bresson', knownFor: 'A master of candid photography and pioneer of street photography, known for "the decisive moment".' },
  { id: 86, name: 'Diane Arbus', knownFor: 'Striking black-and-white portraits of marginalized people and unconventional subjects.' },
  { id: 87, name: 'Richard Avedon', knownFor: 'Revolutionary fashion and portrait photographer with a minimalist, character-revealing style.' },
  { id: 88, name: 'Robert Mapplethorpe', knownFor: 'Controversial and highly stylized black-and-white photography, focusing on portraits and classical nudes.' },
  { id: 89, name: 'Cindy Sherman', knownFor: 'Conceptual self-portraits where she embodies various female archetypes and stereotypes.' },
  { id: 90, name: 'Helmut Newton', knownFor: 'Provocative and erotic high-fashion photography with a bold, voyeuristic style.' },
  { id: 91, name: 'Sebastião Salgado', knownFor: 'Epic, long-term social documentary projects in dramatic black-and-white.' },
  { id: 92, name: 'Gregory Crewdson', knownFor: 'Large-scale, cinematic, and surreal photographs of American suburban life.' },
  { id: 93, name: 'David LaChapelle', knownFor: 'Hyper-realistic, surreal, and colorful commercial photography that often satirizes celebrity culture.' },

  // --- Expanded List ---
  { id: 94, name: 'Kazimir Malevich', knownFor: 'Founder of Suprematism, focusing on basic geometric forms, such as circles, squares and lines.' },
  { id: 95, name: 'Marcel Duchamp', knownFor: 'Pioneering Dada and conceptual art, challenging the notion of art itself with "readymades".' },
  { id: 96, name: 'René Magritte', knownFor: 'Belgian surrealist who created witty and thought-provoking images that challenge perception.' },
  { id: 97, name: 'Max Ernst', knownFor: 'A primary pioneer of the Dada movement and Surrealism, known for his use of frottage and collage.' },
  { id: 98, name: 'Joan Miró', knownFor: 'Surrealist artist known for his playful, biomorphic forms and bold, primary colors.' },
  { id: 99, name: 'Henri Matisse', knownFor: 'A leader of the Fauvist movement, known for his expressive use of color and fluid, simplified forms.' },
  { id: 100, name: 'Edgar Degas', knownFor: 'Impressionist painter and sculptor known for his depictions of dancers, movement, and modern life.' },
  { id: 101, name: 'Paul Cézanne', knownFor: 'Post-Impressionist painter whose work laid the foundations of the transition to Cubism.' },
  { id: 102, name: 'Mary Cassatt', knownFor: 'American Impressionist painter, known for her intimate portraits of women and children.' },
  { id: 103, name: 'John Singer Sargent', knownFor: 'Masterful and elegant portrait painter with a fluid, confident brushwork.' },
  { id: 104, name: 'James Abbott McNeill Whistler', knownFor: 'Tonalist painter, known for his atmospheric and moody compositions, like "Whistler\'s Mother".' },
  { id: 105, name: 'Gustave Courbet', knownFor: 'A leading figure of the Realism movement, painting scenes of everyday life and unidealized subjects.' },
  { id: 106, name: 'William Blake', knownFor: 'A visionary Romantic poet and artist with a highly personal and mystical style.' },
  { id: 107, name: 'Francisco Goya', knownFor: 'Spanish Romantic painter whose work ranged from royal portraits to dark, haunting explorations of war and madness.' },
  { id: 108, name: 'El Greco', knownFor: 'Spanish Renaissance painter with a dramatic and expressionistic style, elongated figures, and vibrant colors.' },
  { id: 109, name: 'Pieter Bruegel the Elder', knownFor: 'Flemish Renaissance painter of landscapes and peasant scenes, filled with detail and narrative.' },
  { id: 110, name: 'Albrecht Dürer', knownFor: 'German Renaissance artist known for his high-quality woodcuts and detailed, analytical drawings.' },
  { id: 111, name: 'Os Gêmeos', knownFor: 'Brazilian twin brothers creating vibrant, yellow-skinned characters in large-scale murals.' },
  { id: 112, name: 'Blu', knownFor: 'Italian street artist creating epic, politically charged murals with a raw, illustrative style.' },
  { id: 113, name: 'Roa', knownFor: 'Belgian street artist known for his large-scale black and white paintings of animals, often showing their skeletons.' },
  { id: 114, name: 'Art Spiegelman', knownFor: 'The creator of "Maus," using a stark, minimalist style to tell a powerful story of the Holocaust.' },
  { id: 115, name: 'Yusuke Murata', knownFor: 'The artist for "One-Punch Man," with exceptionally clean, dynamic, and detailed action sequences.' },
  { id: 116, name: 'Tsutomu Nihei', knownFor: 'Manga artist known for his dark, cyberpunk, and mega-structural architectural style ("Blame!").' },
  { id: 117, name: 'Alan Lee', knownFor: 'Fantasy artist known for his detailed watercolor paintings and conceptual work on "The Lord of the Rings" films.' },
  { id: 118, name: 'John Howe', knownFor: 'Fantasy artist known for his powerful, realistic depictions of dragons and epic scenes for "The Lord of the Rings".' },
  { id: 119, name: 'Boris Vallejo', knownFor: 'Fantasy and erotica artist known for his hyper-realistic paintings of muscular heroes and monsters.' },
  { id: 120, name: 'Julie Bell', knownFor: 'Fantasy artist known for her "metal flesh" technique, creating a powerful, sculptural look for her subjects.' },
  { id: 121, name: 'Weegee', knownFor: 'Gritty and sensationalistic black-and-white street photography of New York crime and nightlife.' },
  { id: 122, name: 'Man Ray', knownFor: 'Surrealist photographer and painter, known for his experimental techniques like solarization.' },
  { id: 123, name: 'Dorothea Lange', knownFor: 'Influential documentary photographer, famous for her Depression-era work like "Migrant Mother".' },
  { id: 124, name: 'Yoji Shinkawa', knownFor: 'Lead artist for the "Metal Gear Solid" series, with a dynamic, sumi-e inspired mecha and character design style.' },
  { id: 125, name: 'Ayami Kojima', knownFor: 'Artist for the "Castlevania" series, known for her elegant, gothic, and bishōnen character designs.' },
  { id: 126, name: 'Craig Mullins', knownFor: 'A pioneering digital painter and concept artist with a loose, painterly, and atmospheric style.' },
  { id: 127, name: 'Ian McQue', knownFor: 'Concept artist known for his rusty, weathered, and atmospheric paintings of futuristic vehicles and environments.' },
  { id: 128, name: 'Feng Zhu', knownFor: 'Prominent concept artist and educator with a focus on functional and detailed environment and vehicle design.' },
  { id: 129, name: 'Sparth (Nicolas Bouvier)', knownFor: 'Concept artist for the "Halo" series, with a bold, graphic, and abstract approach to sci-fi design.' },
  { id: 130, name: 'Zaha Hadid', knownFor: 'Deconstructivist architect known for her futuristic, parametric, and curving building designs.' },
  { id: 131, name: 'Frank Lloyd Wright', knownFor: 'American architect who pioneered the Prairie School movement with an emphasis on organic architecture.' },
  { id: 132, name: 'Antoni Gaudí', knownFor: 'Catalan Modernisme architect known for his highly individual, nature-inspired, and sculptural designs.' },
  { id: 133, name: 'Auguste Rodin', knownFor: 'A master sculptor considered the progenitor of modern sculpture, known for his expressive and realistic figures like "The Thinker".' },
  { id: 134, name: 'Michelangelo', knownFor: 'High Renaissance master of sculpture, painting, and architecture, famed for works like the statue of "David" and the Sistine Chapel ceiling.' },
  { id: 135, name: 'Donatello', knownFor: 'Early Renaissance sculptor who created realistic and emotionally expressive works.' },
  { id: 136, name: 'Gian Lorenzo Bernini', knownFor: 'The leading sculptor of the Baroque period, known for his dynamic, dramatic, and lifelike marble statues.' },
  { id: 137, name: 'Alexander McQueen', knownFor: 'Avant-garde fashion designer known for his theatrical, dark, and masterfully tailored collections.' },
  { id: 138, name: 'Issey Miyake', knownFor: 'Japanese fashion designer known for his technology-driven, pleated, and architectural clothing.' },
  { id: 139, name: 'Yohji Yamamoto', knownFor: 'Japanese fashion designer known for his oversized, dark, and deconstructed avant-garde aesthetic.' },
  { id: 140, name: 'Rick Owens', knownFor: 'Fashion designer with a "glunge" (glamour meets grunge) aesthetic, featuring brutalist forms and a dark palette.' },
  { id: 141, name: 'Vivienne Westwood', knownFor: 'An architect of punk rock fashion, known for her rebellious, theatrical, and historically inspired designs.' },
  { id: 142, name: 'Saul Bass', knownFor: 'Graphic designer and filmmaker, known for his iconic movie posters and title sequences with a minimalist, symbolic style.' },
  { id: 143, name: 'Paul Rand', knownFor: 'A master of modernist graphic design, creating iconic corporate logos for IBM, UPS, and ABC.' },
  { id: 144, name: 'Storm Thorgerson (Hipgnosis)', knownFor: 'Graphic designer who created surreal and iconic album covers for bands like Pink Floyd and Led Zeppelin.' },
  { id: 145, name: 'Peter Saville', knownFor: 'Graphic designer with a minimalist, post-punk aesthetic, famous for his work with Factory Records (Joy Division, New Order).' },
  { id: 146, name: 'Wes Anderson', knownFor: 'Film director with a highly distinctive visual style featuring symmetrical compositions, limited color palettes, and meticulous production design.' },
  { id: 147, name: 'Guillermo del Toro', knownFor: 'Film director known for his dark fantasy films, intricate creature designs, and gothic, fairy-tale aesthetics.' },
  { id: 148, name: 'David Lynch', knownFor: 'Filmmaker and artist known for his surreal, unsettling, and dreamlike films that explore the dark side of American life.' },
  { id: 149, name: 'Stanley Kubrick', knownFor: 'A meticulous and visionary filmmaker known for his striking cinematography, one-point perspective, and diverse genres.' },
  { id: 150, name: 'Akira Kurosawa', knownFor: 'Legendary Japanese film director, a master of composition, movement, and epic storytelling.' },
  { id: 151, name: 'Andrei Tarkovsky', knownFor: 'Russian filmmaker known for his slow, poetic, and metaphysical films with long takes and stunning visuals.' },
  { id: 152, name: 'Genndy Tartakovsky', knownFor: 'Animator known for his highly stylized, graphic, and action-oriented shows like "Samurai Jack" and "Primal".' },
  { id: 153, name: 'Tex Avery', knownFor: 'Animator and cartoon director, a master of surreal gags, exaggerated expressions, and fast-paced comedy in classic Hollywood cartoons.' },
  { id: 154, name: 'Ralph Bakshi', knownFor: 'Pioneer of adult animation, with a gritty, urban, and often controversial style using rotoscoping.' },
  { id: 155, name: 'Don Bluth', knownFor: 'Animator and director known for his lush, detailed, and often darker style of animated films ("The Secret of NIMH").' },
  { id: 156, name: 'Eyvind Earle', knownFor: 'Artist known for his background illustration work for Disney, with a distinct, stylized, and gothic look ("Sleeping Beauty").' },
  { id: 157, name: 'Mary Blair', knownFor: 'Disney artist and concept painter known for her whimsical, stylized, and vibrant color palettes.' },
  { id: 158, name: 'Dr. Seuss (Theodor Geisel)', knownFor: 'The creator of whimsical, surreal children\'s books with a unique and imaginative illustration style.' },
  { id: 159, name: 'Shel Silverstein', knownFor: 'Author and illustrator known for his simple, quirky, and profound black-and-white line drawings.' },
  { id: 160, name: 'Maurice Sendak', knownFor: 'Illustrator of "Where the Wild Things Are," with a cross-hatched, expressive, and sometimes dark style.' },
  { id: 161, name: 'Tove Jansson', knownFor: 'The creator of the Moomins, with a charming, simple, and melancholic black-and-white illustration style.' },
  { id: 162, name: 'Gustave Doré', knownFor: 'A prolific 19th-century illustrator known for his dramatic, detailed, and dark engravings for classic literature.' },
  { id: 163, name: 'Arthur Rackham', knownFor: 'Golden Age illustrator known for his intricate, whimsical, and slightly sinister pen-and-ink and watercolor illustrations.' },
  { id: 164, name: 'Kay Nielsen', knownFor: 'Golden Age illustrator with a highly decorative and elegant style, influenced by Art Nouveau and Japanese woodcuts.' },
  { id: 165, name: 'Edmund Dulac', knownFor: 'Golden Age illustrator known for his rich, jewel-toned, and magical watercolor illustrations.' },
  { id: 166, name: 'John Tenniel', knownFor: 'The original illustrator of "Alice\'s Adventures in Wonderland," with a precise and iconic Victorian engraving style.' },
  { id: 167, name: 'Wayne Barlowe', knownFor: 'Artist known for his realistic and scientifically plausible depictions of aliens and demonic creatures.' },
  { id: 168, name: 'Chesley Bonestell', knownFor: 'A pioneer of space art, creating realistic paintings of space exploration and astronomical scenes.' },
  { id: 169, name: 'John Berkey', knownFor: 'Sci-fi artist with a painterly, impressionistic style, known for his dynamic paintings of spaceships and technology.' },
  { id: 170, name: 'Chris Foss', knownFor: 'Sci-fi artist known for his colorful, massive, and often weathered spaceships and futuristic cityscapes.' },
  { id: 171, name: 'Jim Henson', knownFor: 'Master puppeteer and creator of The Muppets, known for his expressive and imaginative character designs.' },
  { id: 172, name: 'Ray Harryhausen', knownFor: 'A master of stop-motion animation, bringing mythological creatures and dinosaurs to life with a distinctive, kinetic style.' },
  { id: 173, name: 'Phil Tippett', knownFor: 'Stop-motion and VFX legend, a master of creature design and animation for films like "Star Wars" and "Jurassic Park".' },
  { id: 174, name: 'Stan Winston', knownFor: 'A legendary special effects and creature makeup artist, creating iconic characters for "Terminator", "Aliens", and "Jurassic Park".' },
  { id: 175, name: 'Takashi Murakami', knownFor: 'Superflat artist who blurs the line between high and low art, with a colorful, psychedelic, and anime-inspired style.' },
  { id: 176, name: 'Yayoi Kusama', knownFor: 'Avant-garde artist known for her obsessive use of polka dots, infinity nets, and immersive installations.' },
  { id: 177, name: 'Damien Hirst', knownFor: 'A leading figure of the Young British Artists, known for his conceptual art exploring themes of life and death.' },
  { id: 178, name: 'Jeff Koons', knownFor: 'An artist known for his pop-culture inspired, highly polished sculptures of everyday objects, like balloon animals.' },
  { id: 179, name: 'Mark Ryden', knownFor: 'A key figure in Pop Surrealism, with a highly polished, detailed style that mixes cute, nostalgic imagery with unsettling themes.' },
  { id: 180, name: 'Tara McPherson', knownFor: 'Pop Surrealist artist with a distinctive style featuring lonely, ethereal characters and a soft, muted color palette.' },
  { id: 181, name: 'Audrey Kawasaki', knownFor: 'An artist known for her delicate, erotic, and melancholic paintings of young women on wood panels.' },
  { id: 182, name: 'Katsushika Hokusai', knownFor: 'Japanese ukiyo-e artist of the Edo period, famous for the woodblock print series "Thirty-six Views of Mount Fuji", which includes "The Great Wave".' },
  { id: 183, name: 'Utagawa Hiroshige', knownFor: 'One of the last great masters of ukiyo-e, known for his landscapes and series like "The Fifty-three Stations of the Tōkaidō".' },
  { id: 184, name: 'Johannes Vermeer', knownFor: 'Dutch Baroque painter known for his masterful use of light and intimate domestic scenes.' },
  { id: 185, name: 'Sandro Botticelli', knownFor: 'Italian painter of the Early Renaissance, famous for his mythological paintings like "The Birth of Venus".' },
  { id: 186, name: 'Diego Velázquez', knownFor: 'Leading artist of the Spanish Golden Age, a master of portraiture and realism, known for "Las Meninas".' },
  { id: 187, name: 'Eugène Delacroix', knownFor: 'Leader of the French Romantic school, known for his expressive brushstrokes and dramatic historical scenes.' },
  { id: 188, name: 'Caspar David Friedrich', knownFor: '19th-century German Romantic landscape painter, known for his allegorical landscapes and contemplative figures.' },
  { id: 189, name: 'Jacek Yerka', knownFor: 'Polish surrealist painter who creates fantastical, idyllic, and dreamlike worlds with incredible detail.' },
  { id: 190, name: 'Gerhard Richter', knownFor: 'German visual artist who has produced abstract and photorealistic paintings, as well as photographs and glass pieces.' },
  { id: 191, name: 'David Hockney', knownFor: 'An influential British artist of the Pop art movement, known for his vibrant paintings of swimming pools and portraits.' },
  { id: 192, name: 'Jenny Saville', knownFor: 'Contemporary British painter known for her large-scale, monumental paintings of the nude female form.' },
  { id: 193, name: 'Anish Kapoor', knownFor: 'British Indian sculptor known for his large-scale, abstract, and often reflective public sculptures.' },
  { id: 194, name: 'Ai Weiwei', knownFor: 'A contemporary Chinese artist and activist, known for his conceptual art that critiques social and political issues.' },
  { id: 195, name: 'Olafur Eliasson', knownFor: 'Danish-Icelandic artist known for large-scale installation art employing elemental materials such as light, water, and air temperature.' },
  { id: 196, name: 'Kara Walker', knownFor: 'American contemporary artist known for her room-size tableaux of black cut-paper silhouettes that explore race, gender, and sexuality.' },
  { id: 197, name: 'Kehinde Wiley', knownFor: 'A portrait painter known for his highly naturalistic paintings of Black people in heroic poses, referencing Old Master paintings.' },
  { id: 198, name: 'Bridget Riley', knownFor: 'An English painter who is one of the foremost proponents of Op art.' },
  { id: 199, name: 'Frank Stella', knownFor: 'An American painter and sculptor, a key figure in minimalism and post-painterly abstraction.' },
  { id: 200, name: 'Cy Twombly', knownFor: 'American painter known for his large-scale, calligraphic, and graffiti-like works.' },
  { id: 201, name: 'Lucian Freud', knownFor: 'British painter known for his thickly impastoed and unsettling portraits and figure paintings.' },
  { id: 202, name: 'Edward Hopper', knownFor: 'An American realist painter, known for his depictions of urban and rural scenes that convey a sense of loneliness and isolation.' },
  { id: 203, name: 'Grant Wood', knownFor: 'American painter known for his paintings depicting the rural American Midwest, as in his famous painting "American Gothic".' },
  { id: 204, name: 'Thomas Cole', knownFor: 'Founder of the Hudson River School, an American art movement known for its romantic and detailed landscape paintings.' },
  { id: 205, name: 'Winslow Homer', knownFor: 'American landscape painter and printmaker, best known for his marine subjects.' },
  { id: 206, name: 'Andrew Wyeth', knownFor: 'Realist painter, known for his regionalist style and muted palette, as seen in "Christina\'s World".' },
  { id: 207, name: 'Thomas Kinkade', knownFor: 'A painter of popular, idyllic, and pastoral scenes with glowing highlights and saturated colors.' },
  { id: 208, name: 'Bob Ross', knownFor: 'American painter and television host, known for his "wet-on-wet" oil painting technique and creating serene, happy landscapes.' },
  { id: 209, name: 'Ruan Jia', knownFor: 'A highly influential fantasy concept artist and illustrator with a detailed, atmospheric, and painterly style.' },
  { id: 210, name: 'Kim Jung Gi', knownFor: 'A legendary South Korean artist known for his massive, intricate, and improvised drawings from memory.' },
  { id: 211, name: 'Ashley Wood', knownFor: 'Australian comic book artist and illustrator known for his expressive, stylized, and often gritty paintings of robots and figures.' },
  { id: 212, name: 'Simon Stålenhag', knownFor: 'Swedish artist known for his digital paintings of retro-futuristic, sci-fi scenes in mundane Swedish landscapes.' },
  { id: 213, name: 'Greg Rutkowski', knownFor: 'A Polish fantasy illustrator known for his dramatic, epic, and painterly style with a focus on lighting.' },
  { id: 214, name: 'Magali Villeneuve', knownFor: 'A fantasy illustrator known for her detailed, character-focused, and elegant work for "Magic: The Gathering" and "A Song of Ice and Fire".' },
  { id: 215, name: 'Rebecca Guay', knownFor: 'An artist known for her ethereal, watercolor-based, and Art Nouveau-inspired fantasy illustrations.' },
  { id: 216, name: 'Terese Nielsen', knownFor: 'An influential fantasy artist with a versatile, realistic, and often spiritual style, famous for her "Magic: The Gathering" work.' },
  { id: 217, name: 'John Avon', knownFor: 'A legendary fantasy artist, famous for his vibrant, atmospheric, and iconic landscape paintings for "Magic: The Gathering".' },
  { id: 218, name: 'Posuka Demizu', knownFor: 'The artist for the manga "The Promised Neverland", known for her intricate, detailed, and dynamic illustration style.' },
  { id: 219, name: 'Q-HAYASHIDA', knownFor: 'The creator of "Dorohedoro," with a gritty, chaotic, and punk-rock manga art style.' },
  { id: 220, name: 'Hiromu Arakawa', knownFor: 'The creator of "Fullmetal Alchemist," known for her clean, expressive style and excellent paneling.' },
  { id: 221, name: 'Shinichiro Watanabe', knownFor: 'Anime director known for his stylish, genre-blending works with strong musical influences, like "Cowboy Bebop" and "Samurai Champloo".' },
  { id: 222, name: 'Yoshiaki Kawajiri', knownFor: 'Anime director known for his dark, stylish, and action-packed films like "Ninja Scroll" and "Vampire Hunter D: Bloodlust".' },
  { id: 223, name: 'Hideaki Anno', knownFor: 'The creator of "Neon Genesis Evangelion," known for his experimental direction and exploration of deep psychological themes.' },
  { id: 224, name: 'Mamoru Oshii', knownFor: 'Director of the 1995 "Ghost in the Shell" film, known for his philosophical, atmospheric, and visually dense anime.' },
  { id: 225, name: 'Isao Takahata', knownFor: 'Co-founder of Studio Ghibli, known for his realistic and emotionally powerful animated films like "Grave of the Fireflies".' },
  { id: 226, name: 'Makoto Shinkai', knownFor: 'Anime director known for his visually stunning, emotional, and romantic films with hyper-realistic backgrounds.' },
  { id: 227, name: 'Masaaki Yuasa', knownFor: 'Anime director with a wild, fluid, and highly expressive animation style, as seen in "Devilman Crybaby" and "Ping Pong".' },
  { id: 228, name: 'Koji Morimoto', knownFor: 'An animator and director known for his experimental, surreal, and highly detailed short films and contributions to works like "Akira".' },
  { id: 229, name: 'Peter Chung', knownFor: 'The creator of "Æon Flux," with a distinctive, angular, and fashion-forward animation style.' },
  { id: 230, name: 'Takeshi Koike', knownFor: 'Anime director and animator with a high-contrast, dynamic, and stylized visual style, as seen in "Redline".' },
  { id: 231, name: 'Range Murata', knownFor: 'Japanese artist and designer known for his detailed, retro-futuristic character designs with a focus on fashion.' },
  { id: 232, name: 'Tatsuyuki Tanaka', knownFor: 'An animator and illustrator with a detailed, gritty, and industrial aesthetic, known for his work on "Akira" and his artbook "Cannabis Works".' },
  { id: 233, name: 'Katsuya Terada', knownFor: 'The "Doodle King," a Japanese artist with a masterful, imaginative, and often erotic fantasy and sci-fi style.' },
  { id: 234, name: 'Sorayama', knownFor: 'A Japanese illustrator famous for his precisely detailed, erotic, and robotic "sexy robot" paintings.' },
  { id: 235, name: 'Artgerm (Stanley Lau)', knownFor: 'A digital artist and illustrator known for his polished, semi-realistic, and stylish portraits of comic book and video game characters.' },
  { id: 236, name: 'Loish (Lois van Baarle)', knownFor: 'A digital artist known for her vibrant, stylized, and flowing character illustrations with a focus on color and light.' },
  { id: 237, name: 'Ross Tran (Rossdraws)', knownFor: 'A digital artist and YouTuber known for his colorful, painterly, and character-focused concept art and illustrations.' },
];
