
import type { Costume } from '../types';

export const COSTUMES: Costume[] = [
  // Iconic Movie & TV Villains
  { id: 1, name: 'Ghostface (Scream)' },
  { id: 2, name: 'Freddy Krueger (A Nightmare on Elm Street)' },
  { id: 3, name: 'Jason Voorhees (Friday the 13th)' },
  { id: 4, name: 'Michael Myers (Halloween)' },
  { id: 5, name: 'Hell Priest (Cenobite)' },
  { id: 6, name: 'Chainsaw-Wielding Cannibal' },
  { id: 7, name: 'Chucky (Child\'s Play)' },
  { id: 8, name: 'Pennywise the Dancing Clown (IT)' },
  { id: 9, name: 'Game Master Puppet (Saw)' },
  { id: 10, name: 'Sam (Trick \'r Treat)' },
  { id: 11, name: 'The Terrifying Mime' },
  { id: 12, name: 'Captain Spaulding (House of 1000 Corpses)' },
  { id: 13, name: 'The Nun (Valak)' },
  { id: 14, name: 'Annabelle Doll' },
  { id: 15, name: 'The Sophisticated Cannibal' },
  { id: 16, name: 'Norman Bates as Mother (Psycho)' },
  { id: 17, name: 'The Possessed Girl (Exorcist)' },
  { id: 18, name: 'Carrie White (Prom Dress)' },
  { id: 19, name: 'Jack Torrance (The Shining)' },
  { id: 20, name: 'Wall Street Psycho' },
  { id: 21, name: 'Alex DeLarge (A Clockwork Orange)' },
  { id: 22, name: 'Candyman' },
  { id: 23, name: 'The Creeper (Jeepers Creepers)' },
  { id: 24, name: 'Dracula (Classic)' },
  { id: 25, name: 'Frankenstein\'s Monster' },
  { id: 26, name: 'The Wolf Man' },
  { id: 27, name: 'The Mummy' },
  { id: 28, name: 'Creature from the Black Lagoon' },
  { id: 29, name: 'The Invisible Man' },
  { id: 30, name: 'Bride of Frankenstein' },
  { id: 31, name: 'The Babadook' },
  { id: 32, name: 'The Tethered (Us)' },
  { id: 33, name: 'Black Phillip (The Witch)' },
  { id: 34, name: 'Kayako Saeki (The Grudge)' },
  { id: 35, name: 'Sadako/Samara (The Ring)' },
  { id: 36, name: 'Demogorgon (Stranger Things)' },
  { id: 37, name: 'Twisty the Clown (American Horror Story)' },
  { id: 38, name: 'Vecna (Stranger Things)' },
  { id: 39, name: 'M3GAN' },
  { id: 40, name: 'Pearl' },
  { id: 41, name: 'The Grabber (The Black Phone)' },
  { id: 42, name: 'Xenomorph (Alien)' },
  { id: 43, name: 'Predator' },
  { id: 44, name: 'The Thing (Outpost 31)' },
  { id: 45, name: 'Beetlejuice' },
  { id: 46, name: 'Edward Scissorhands' },
  { id: 47, name: 'The Crow' },
  { id: 48, name: 'Joker (Classic)' },
  { id: 49, name: 'Harley Quinn (Classic)' },
  { id: 50, name: 'Scarecrow (Batman)' },

  // Classic & Folklore Monsters
  { id: 51, name: 'Vampire' },
  { id: 52, name: 'Werewolf' },
  { id: 53, name: 'Zombie' },
  { id: 54, name: 'Ghost' },
  { id: 55, name: 'Skeleton' },
  { id: 56, name: 'Witch' },
  { id: 57, name: 'Devil / Demon' },
  { id: 58, name: 'Scarecrow' },
  { id: 59, name: 'Headless Horseman' },
  { id: 60, name: 'Banshee' },
  { id: 61, name: 'Ghoul' },
  { id: 62, name: 'Goblin' },
  { id: 63, name: 'Gremlin' },
  { id: 64, name: 'Imp' },
  { id: 65, name: 'Lich' },
  { id: 66, name: 'Grim Reaper' },
  { id: 67, name: 'Siren' },
  { id: 68, name: 'Wendigo' },
  { id: 69, name: 'Krampus' },
  { id: 70, name: 'Mothman' },
  { id: 71, name: 'Skinwalker' },
  { id: 72, name: 'Baba Yaga' },
  { id: 73, name: 'Gargoyle' },
  { id: 74, name: 'Medusa' },
  { id: 75, name: 'Minotaur' },
  { id: 76, name: 'Cyclops' },
  { id: 77, name: 'Cthulhu' },
  { id: 78, name: 'Doppelgänger' },
  { id: 79, name: 'Fairy (Dark)' },
  { id: 80, name: 'Gnome (Malevolent)' },

  // Horror Tropes & Archetypes
  { id: 81, name: 'Plague Doctor' },
  { id: 82, name: 'Possessed Doll' },
  { id: 83, name: 'Evil Clown' },
  { id: 84, name: 'Mad Scientist' },
  { id: 85, name: 'Butcher' },
  { id: 86, name: 'Voodoo Doll' },
  { id: 87, name: 'Creepy Butler' },
  { id: 88, name: 'Undead Prom Queen' },
  { id: 89, name: 'Ghostly Bride' },
  { id: 90, name: 'Shadow Person' },
  { id: 91, name: 'Sleep Paralysis Demon' },
  { id: 92, name: 'Anthropophagist' },
  { id: 93, name: 'Cultist' },
  { id: 94, name: 'Zombie Hunter' },
  { id: 95, name: 'Vampire Hunter' },
  { id: 96, name: 'Mad Hatter (Dark version)' },
  { id: 97, name: 'Evil Jester' },
  { id: 98, name: 'Ringmaster of a Dark Circus' },
  { id: 99, name: 'Haunted Marionette' },
  { id: 100, name: 'Killer Robot' },
  { id: 101, name: 'Fortune Teller (Cursed)' },
  { id: 102, name: 'Grave Digger' },
  { id: 103, name: 'Executioner' },
  { id: 104, name: 'Mannequin (Living)' },
  { id: 105, name: 'Sideshow Freak' },
  { id: 106, name: 'Ventriloquist Dummy' },
  { id: 107, name: 'Zombie Doctor/Nurse' },
  { id: 108, name: 'Ghost Pirate' },
  { id: 109, name: 'Infamous Slayer' },
  { id: 110, name: 'Corrupt Politician' },
  { id: 111, name: 'Killer Scarecrow' },
  { id: 112, name: 'Unhinged Doctor' },
  { id: 113, name: 'Child with an Inner Demon' },
  { id: 114, name: 'Fallen Angel' },
  { id: 115, name: 'Haunted Armor' },
  { id: 116, name: 'Creepy Gardner' },
  { id: 117, name: 'Wicked Queen' },
  { id: 118, name: 'Dark Sorcerer' },
  { id: 119, name: 'Psychopathic Patient' },
  { id: 120, name: 'Evil Toy Soldier' },

  // Undead & Body Horror
  { id: 121, name: 'Zombie (Classic Shambler)' },
  { id: 122, name: 'Zombie (Fast/Infected)' },
  { id: 123, name: 'Freshly Dug-Up Corpse' },
  { id: 124, name: 'Reanimated Corpse (Frankenstein style)' },
  { id: 125, name: 'Patchwork Person' },
  { id: 126, name: 'Living Anatomy Model' },
  { id: 127, name: 'Unstable Medical Subject' },
  { id: 128, name: 'Fungal Zombie (Cordyceps)' },
  { id: 129, name: 'Body with Trypophobia Holes' },
  { id: 130, name: 'Human Spider Hybrid' },
  { id: 131, name: 'Amalgam of Melted Toys' },
  { id: 132, name: 'Person with Visible Insides' },
  { id: 133, name: 'Roadkill' },
  { id: 134, name: 'Crash Test Dummy (Damaged)' },
  { id: 135, name: 'Human Pincushion' },
  { id: 136, name: 'Jiangshi (Hopping Vampire)' },
  { id: 137, name: 'Revenant' },
  { id: 138, name: 'Draugr' },
  { id: 139, name: 'Mummy (Rotting)' },
  { id: 140, name: 'Skeleton Warrior' },

  // Gothic & Victorian
  { id: 141, name: 'Victorian Ghost' },
  { id: 142, name: 'Gothic Vampire' },
  { id: 143, name: 'Steampunk Monster Hunter' },
  { id: 144, name: 'Edgar Allan Poe' },
  { id: 145, name: 'Victorian Night Stalker' },
  { id: 146, name: 'Mourner at a Funeral' },
  { id: 147, name: 'Haunted Portrait' },
  { id: 148, name: 'Headless Aristocrat' },
  { id: 149, name: 'Possessed Nun' },
  { id: 150, name: 'Corrupt Priest' },

  // Creepy Animals & Creatures
  { id: 151, name: 'Black Cat' },
  { id: 152, name: 'Bat' },
  { id: 153, name: 'Spider' },
  { id: 154, name: 'Raven / Crow' },
  { id: 155, name: 'Snake' },
  { id: 156, name: 'Rat' },
  { id: 157, name: 'Giant Cockroach' },
  { id: 158, name: 'Hellhound' },
  { id: 159, name: 'Human Fly Hybrid' },
  { id: 160, name: 'Cheshire Cat (Creepy)' },
  
  // Assorted & Modern
  { id: 161, name: 'Slender Man' },
  { id: 162, name: 'Grinning Knife Wielder' },
  { id: 163, name: 'The Rake' },
  { id: 164, name: 'Ben Drowned' },
  { id: 165, name: 'Siren Head' },
  { id: 166, name: 'Cartoon Cat' },
  { id: 167, name: 'Annual Anarchist (The Purge)' },
  { id: 168, name: 'Masked Intruder (The Strangers)' },
  { id: 169, name: 'Bigfoot' },
  { id: 170, name: 'Grey Alien' },
  { id: 171, name: 'Reptilian' },
  { id: 172, name: 'Killer Klown from Outer Space' },
  { id: 173, name: 'The Gentlemen (Buffy)' },
  { id: 174, name: 'Weeping Angel (Doctor Who)' },
  { id: 175, name: 'Pyramid Head (Silent Hill)' },
  { id: 176, name: 'Clicker (The Last of Us)' },
  { id: 177, name: 'Big Daddy (BioShock)' },
  { id: 178, name: 'The Keeper (The Evil Within)' },
  { id: 179, name: 'Springtrap (Five Nights at Freddy\'s)' },
  { id: 180, name: 'Huggy Wuggy (Poppy Playtime)' },
  { id: 181, name: 'Miner 49er (Scooby-Doo)' },
  { id: 182, name: 'Cereal Killer' },
  { id: 183, name: 'Killer Teddy Bear' },
  { id: 184, name: 'Evil Garden Gnome' },
  { id: 185, name: 'Creepy Ice Cream Man' },
  { id: 186, name: 'Two-Face (Batman)' },
  { id: 187, name: 'Carnage (Marvel)' },
  { id: 188, name: 'Venom (Marvel)' },
  { id: 189, name: 'Deadpool' },
  { id: 190, name: 'Rorschach (Watchmen)' },
  { id: 191, name: 'The Riddler' },
  { id: 192, name: 'Poison Ivy' },
  { id: 193, name: 'Catwoman' },
  { id: 194, name: 'Maleficent' },
  { id: 195, name: 'Cruella de Vil' },
  { id: 196, name: 'Ursula' },
  { id: 197, name: 'Captain Hook' },
  { id: 198, name: 'The Other Mother (Coraline)' },
  { id: 199, name: 'Lord Voldemort' },
  { id: 200, name: 'Dementor (Harry Potter)' },
];
