import type { Creature } from '../types';

export const CREATURES: Creature[] = [
  // --- BLANK CANVAS ---
  { id: 0, name: 'Blank Canvas Bear', description: 'A plain, featureless teddy bear. A perfect vessel, ready to be defined entirely by its disguise and mutations.' },
  
  // --- CARNIVAL & CLOWN HORROR (Untouched as per request) ---
  { id: 1, name: 'Wicked Clown Teddy Bear', description: 'A sinister carnival nightmare made of stained plush. Its face is a cracked mask of greasepaint, with a permanent, malicious grin stitched into its fabric. It embodies the unsettling juxtaposition of childhood innocence and malevolent circus horror.' },
  { id: 2, name: 'Ringmaster Teddy Bear', description: 'The tyrannical ruler of a dark circus, dressed in a tattered but imposing tailcoat. It commands unseen horrors with an air of authority and dread.' },
  { id: 3, name: 'Sinister Jester Teddy Bear', description: 'A chaotic and unpredictable trickster, adorned in motley patterns and bells that jingle with discordant notes. Its movements are erratic, and its smile hides mad, dangerous secrets.' },
  { id: 8, name: 'Faygo-Stained Teddy Bear', description: 'A sticky, chaotic mess of a bear, permanently stained with the sugary spray of red soda. It represents the frenzied energy of an underground concert, both manic and joyful.' },
  { id: 9, name: 'Dark Carnival Freak Teddy Bear', description: 'A tragic and unsettling sideshow attraction, with misshapen limbs and a sorrowful, stitched-on expression. It is a creature born of exploitation and neglect.' },
  { id: 10, name: 'Hatchet-Man Teddy Bear', description: 'A loyal and menacing enforcer, its form adorned with the iconic running hatchet-man symbol. It represents a fierce, cult-like devotion and a readiness for violence.' },
  { id: 11, name: 'Spirit of the Lotus Teddy Bear', description: 'A mystical bear that seems to be a vessel for a dark, ethereal power. It\'s adorned with faded lotus symbols, representing a corrupted form of enlightenment and inner peace.' },

  // --- SUPERNATURAL & PARANORMAL HORROR ---
  { id: 4, name: 'The Onryō Bear (Vengeful Spirit)', description: 'A specter of Japanese horror (e.g., The Ring, The Grudge). Its face is obscured by a curtain of long, stringy black hair, and it moves with an unnatural, joint-snapping crawl. It is the embodiment of a potent curse.' },
  { id: 5, name: 'The Poltergeist Bear', description: 'It floats menacingly, the epicenter of a storm of telekinetically thrown objects (e.g., Poltergeist). It isn\'t just haunted; it is the invisible, violent rage of a troubled spirit given form.' },
  { id: 6, name: 'The Sleep Paralysis Demon Bear', description: 'A being of pure shadow and static, with indistinct features except for glowing white eyes. Its form is heavy and oppressive, a silent watcher that appears in the corner of your room at night (e.g., The Nightmare).' },
  { id: 7, name: 'The Haunted Doll Bear', description: 'Its plush body is fused with the cracked porcelain face and dead glass eyes of an antique doll (e.g., Annabelle, Chucky). It moves when you aren\'t looking, a silent, watchful vessel for something ancient and malevolent.' },
  { id: 12, name: 'The Body Snatcher Bear (The Uncanny Thing)', description: 'It looks like a normal teddy bear at a glance, but its proportions are subtly wrong, its smile too wide, its button eyes too deep. It is a perfect, terrifying imitation of something beloved (e.g., Invasion of the Body Snatchers).' },
  { id: 13, name: 'The Banshee Bear', description: 'Its mouth is frozen in a silent, agonizing scream, and an ethereal wail follows it, heralding doom. Its fur is pale and translucent, a harbinger of death (e.g., Irish folklore).' },
  { id: 14, name: 'The Shadow Person Bear', description: 'A stark, bear-shaped silhouette of pure, flat darkness. It has no features and is only seen in your peripheral vision, vanishing when looked at directly. A being from the corner of your eye (e.g., common paranormal encounters).' },
  { id: 15, name: 'The Dybbuk Box Bear', description: 'An old, worn bear trapped inside a small wooden box sealed with wax and covered in carved warnings. Opening the box unleashes the malevolent entity that possesses the toy (e.g., The Possession).' },

  // --- BODY HORROR & MEDICAL GORE ---
  { id: 16, name: 'The Flesh-Stitched Bear (The Patchwork)', description: 'A grotesque amalgam of different fabrics, stained plush, and what appears to be actual skin, crudely sewn together with thick, black thread. A mobile testament to a mad creator\'s vision (e.g., Frankenstein, Leatherface).' },
  { id: 17, name: 'The Fungal Host Bear (Cordyceps)', description: 'Its body is a walking ecosystem for a parasitic fungus. Colorful, grotesque mushrooms sprout from its seams, and its head has split open into a blooming fungal plate that releases spores (e.g., The Last of Us, Annihilation).' },
  { id: 18, name: 'The Flayed Bear', description: 'Its plush \'skin\' has been peeled back in grotesque flaps and pinned open, revealing the raw, red muscle, sinew, and glistening organs beneath. A living anatomy lesson in agony (e.g., Hellraiser, Hannibal Lecter).' },
  { id: 19, name: 'The Failed Experiment Bear', description: 'A medical horror strapped to a rusty gurney, its body a mess of hypodermic needles, weeping sutures, and pulsing tubes connected to leaking chemical bags. A procedure gone horribly wrong (e.g., Re-Animator, The Fly).' },
  { id: 20, name: 'The Viscera-Stuffed Bear', description: 'Its seams are splitting not with cotton, but with glistening, realistic guts and organs that seem to pulse and squirm with a life of their own. A gruesome, walking piñata of gore (e.g., splatter films, autopsy scenes).' },
  { id: 21, name: 'The Trypophobia Bear', description: 'Its entire body is covered in a pattern of deep, unsettling holes and clusters. The texture is maddening, and dark shapes seem to writhe within the cavities (e.g., American Horror Story: Cult).' },
  { id: 22, name: 'The Arachnid Host Bear', description: 'A mummified-looking bear, its body is a living nest for thousands of spiders that swarm and crawl in and out of its mouth and eye sockets. Its limbs have been replaced with long, spindly spider legs (e.g., Arachnophobia).' },
  { id: 23, name: 'The Living Anatomy Bear', description: 'Its skin is a translucent gel, revealing a perfectly detailed and functioning system of organs, muscles, and bones within. A walking, breathing anatomical model with a beating heart (e.g., Visible Man model).' },
  { id: 24, name: 'The Amalgam Bear', description: 'Not stitched, but melted and fused together from dozens of other plastic and plush toys into a single, writhing, multi-limbed mass. Many faces, trapped in the plastic, scream in silent agony (e.g., Sid\'s toys from Toy Story, Tetsuo: The Iron Man).' },

  // --- SLASHER & PSYCHOLOGICAL HORROR ---
  { id: 25, name: 'The Giallo Bear (Black-Gloved Killer)', description: 'Dressed in a sleek trench coat, its paws are replaced with black leather gloves. One glove wields a straight razor. Its face is an emotionless mask, embodying the stylish, mysterious killers of Italian horror (e.g., Dario Argento films).' },
  { id: 26, name: 'The Slasher Bear (The Stalker)', description: 'Wears a generic, featureless white mask and wields a large, bloody kitchen knife. It is the embodiment of a relentless, silent, and unstoppable killer that stalks suburbia on Halloween night (e.g., Halloween, Friday the 13th).' },
  { id: 27, name: 'The Cannibal Butcher Bear', description: 'A grimy, hulking figure clad in a blood-stained apron made of human skin, wielding a sputtering chainsaw. The deranged scion of a degenerate, backwoods family (e.g., The Texas Chainsaw Massacre).' },
  { id: 28, name: 'The Cenobite Bear (Hell-Priest)', description: 'Its plush form is geometrically scarred and methodically pierced with pins and hooks. An explorer from a dimension of exquisite pain and pleasure, it offers a lamentable configuration (e.g., Hellraiser).' },
  { id: 29, name: 'The Malevolent Toymaker Bear', description: 'Itself a toy, but it crafts smaller, horrifying marionettes from bone and flesh. It has an intelligent, cruel look in its eyes, the master of a show no one wants to see (e.g., Puppet Master).' },
  { id: 30, name: 'The Home Intruder Bear', description: 'Dressed in all black, wearing a terrifyingly simple sack mask with cut-out eyes. It stands silently in the corner of a room, holding a hammer, a manifestation of the fear of being watched in your own home (e.g., The Strangers).' },
  { id: 31, name: 'The Torture Device Bear', description: 'Its body is a fusion of a cuddly toy and a medieval torture device. It is a walking iron maiden, covered in spikes on the inside and out, with thumbscrews for paws (e.g., Saw, Hostel).' },

  // --- COSMIC & SCI-FI HORROR ---
  { id: 32, name: 'The Thing Bear (The Imitator)', description: 'A grotesque, shifting mass of flesh, fur, and teeth that is poorly attempting to form the shape of a teddy bear. A misplaced eye blinks on its shoulder as a tentacle erupts from its back. A perfect imitation of life (e.g., John Carpenter\'s The Thing).' },
  { id: 33, name: 'The Cosmic Horror Bear (Void-Gazer)', description: 'Its fur is the color of the void, dotted with points of light like a distant nebula. Looking into its swirling vortex eyes induces madness. Its form hints at geometries the human mind cannot comprehend (e.g., H.P. Lovecraft).' },
  { id: 34, name: 'The Xenomorph Bear', description: 'A biomechanical nightmare. Its head is an elongated, eyeless, translucent dome. A second, pharyngeal jaw is hidden within its mouth, and its body is a black exoskeleton of tubes and ridges (e.g., Alien franchise).' },
  { id: 35, name: 'The Grey Alien Bear', description: 'A classic "grey" alien in bear form. It has a large, bulbous head, black, almond-shaped eyes, a thin body, and long fingers. It floats silently, an abductor and cold, detached experimenter (e.g., The X-Files, Communion).' },
  { id: 36, name: 'The Glitching Signal Bear (Analog Horror)', description: 'Its face is a flickering television screen displaying distorted, uncanny human faces and cryptic, threatening messages. A low, ominous hum and fragments of hijacked broadcasts emanate from it (e.g., Local 58, The Mandela Catalogue).' },
  { id: 37, name: 'The Liminal Entity Bear (Backrooms Walker)', description: 'A tall, unnaturally elongated bear with limbs that bend at the wrong angles. It stalks the endless, empty, yellow-walled corridors of the Backrooms with impossible speed, its footsteps echoing on the damp carpet (e.g., The Backrooms creepypasta).' },
  { id: 38, name: 'The Color Out of Space Bear', description: 'A bear that seems to be made of a shifting, indescribable color that doesn\'t exist in nature. Looking at it is disorienting and nauseating, and it seems to drain the life and color from everything around it (e.g., H.P. Lovecraft\'s "The Colour Out of Space").' },
  { id: 39, name: 'The Replicator Bear', description: 'A bear made of self-replicating nanites. It can dissolve into a "grey goo" swarm and reform, perfectly consuming and replicating any material it touches, leaving behind only more of itself (e.g., "grey goo" doomsday scenario).' },

  // --- FOLK & CRYPTID HORROR ---
  { id: 40, name: 'The Wendigo Bear', description: 'An emaciated, horrifying creature with a deer skull for a head and elongated, clawed limbs. It embodies insatiable hunger and the terror of a frozen, cannibalistic wilderness (e.g., Pet Sematary, Antlers).' },
  { id: 41, name: 'The Skinwalker Bear', description: 'A gaunt, mangy creature that moves with an unsettling, jerky motion. Its proportions are wrong, and it wears the tattered pelt of another animal. It perfectly mimics the voice of a loved one to lure you into the dark (e.g., Navajo folklore).' },
  { id: 42, name: 'The Mothman Bear', description: 'It has large, feathery insectoid wings, and its eyes are huge, red, and glow with malevolent intelligence. A cryptid of ill omen, its appearance is a harbinger of disaster (e.g., The Mothman Prophecies).' },
  { id: 43, name: 'The Scarecrow Bear', description: 'Stuffed with straw and dressed in tattered burlap, this bear has a menacing, fixed grin stitched onto its sackcloth head. It stands crucified on a wooden cross in a lonely field, moving only when no one is watching (e.g., Jeepers Creepers).' },
  { id: 44, name: 'The Goat-Eyed Bear (Black Phillip)', description: 'A simple, black-furred bear, but its button eyes have been replaced with the cold, horizontal-pupiled eyes of a goat. It walks upright and whispers temptations of worldly pleasures (e.g., The Witch).' },
  { id: 45, name: 'The Krampus Bear', description: 'A festive horror with large, curling goat horns, a long pointed tongue, and cloven hooves. It carries a bundle of birch sticks for swatting the wicked and a sack for carrying them away to hell (e.g., Alpine folklore).' },

  // --- GOTHIC & UNDEAD HORROR ---
  { id: 46, name: 'The Vampire Lord Bear', description: 'An aristocratic and ancient creature of the night. Dressed in a high-collared cape, its plush fur is unnaturally pale. It has sharp fangs, hypnotic eyes, and an aura of tragic, predatory romance (e.g., Bram Stoker\'s Dracula).' },
  { id: 47, name: 'The Zombie Bear (The Shambler)', description: 'A classic undead horror. Its fur is patchy and peeling to reveal rotting, discolored flesh. One eye dangles from its socket, and it shambles forward with an insatiable hunger (e.g., The Walking Dead, Night of the Living Dead).' },
  { id: 48, name: 'The Skeletal Bear', description: 'The plush exterior has rotted away entirely, revealing a perfectly articulated, bear-shaped skeleton underneath. A morbid, clattering anatomical horror animated by pure necromancy (e.g., Jason and the Argonauts).' },
  { id: 49, name: 'The Frankenstein\'s Bear', description: 'A reanimated creature, crudely stitched together from the parts of other, less fortunate toys and animals. Large bolts stick out of its neck, and it moves with a heavy, clumsy, and tragic gait (e.g., Mary Shelley\'s Frankenstein).' },
  { id: 50, name: 'The Plague Doctor Bear', description: 'Its face is hidden behind the iconic beaked mask, its body covered in a long, black, leather coat. It carries an aura of pestilence and grim, archaic medicine, its intentions unknowable (e.g., historical Black Death doctors).' },
  { id: 51, name: 'The Gargoyle Bear', description: 'A stone bear with leathery wings, perpetually perched and motionless. It is a grim, weathered protector that animates at night to hunt, its stone claws scraping on the rooftops (e.g., Gothic architecture).' },
  { id: 52, name: 'The Grave-Hag Bear', description: 'A hunched and withered creature, reeking of swamp water and cemetery dirt. It is a collector of bones and secrets, an ancient and malicious crone in teddy bear form (e.g., European folklore, ghouls).' }
];