import type { EdgyArtStyle } from '../types';

export const EDGY_ART_STYLES: EdgyArtStyle[] = [
  { id: 1, name: 'Heavy Metal Album Cover' },
  { id: 2, name: 'Blackwork Tattoo Flash' },
  { id: 3, name: 'Gothic Horror Illustration' },
  { id: 4, name: 'Crust Punk Zine Photocopy' },
  { id: 5, name: 'Dark Fantasy Concept Art' },
  { id: 6, name: '90s Horror VHS Cover' },
  { id: 7, name: 'Brutalist Architecture Style' },
  { id: 8, name: 'Biomechanical (H.R. Giger)' },
  { id: 9, name: 'Scratched 35mm Film Look' },
  { id: 10, name: 'Cyber-Noir Atmosphere' },
  { id: 11, name: 'Occult Woodcut Print' },
  { id: 12, name: 'Deathrock Batcave Flyer' },
  { id: 13, name: 'Glitchy, Corrupted Datamosh' },
  { id: 14, name: 'Dark Surrealism (Zdzisław Beksiński)' },
  { id: 15, name: 'Gritty Comic Inking (Mike Mignola)' },
  { id: 16, name: 'Post-Apocalyptic Grime' },
  { id: 17, name: 'Industrial Decay Photography' },
  { id: 18, name: 'Lowbrow Pop Surrealism' },
  { id: 19, name: 'Haunted, Overexposed Polaroid' },
  { id: 20, name: 'Medical Abnormality Drawing' },

  // --- Comic & Illustration Styles ---
  { id: 21, name: 'Gritty Noir Comic (Frank Miller)' },
  { id: 22, name: 'Underground Comix Aesthetic (R. Crumb)' },
  { id: 23, name: 'Chaotic Hyper-Detail Linework (Geof Darrow)' },
  { id: 24, name: '90s Extreme Comic Style (Liefeld/McFarlane)' },
  { id: 25, name: 'Psychedelic Sci-Fi Comic (Moebius)' },
  { id: 26, name: 'Airbrushed 80s Fantasy Art (Boris Vallejo)' },
  { id: 27, name: 'Anatomical Cross-Section Illustration' },
  { id: 28, name: 'Technical Blueprint/Schematic' },
  { id: 29, name: 'Heavy Crosshatching & Ink Work' },
  { id: 30, name: 'Sin City High-Contrast Negative Space' },
  { id: 31, name: 'Bold Hellboy Shadows' },
  { id: 32, name: 'Manga Screen Tone Patterns' },
  { id: 33, name: '2000 AD Gritty Sci-Fi (Judge Dredd)' },
  { id: 34, name: 'Vertigo Comics Occult Horror' },
  { id: 35, name: 'EC Comics Style Horror' },
  { id: 36, name: 'Heavy Metal Magazine Fantasy' },
  { id: 37, name: 'Skateboard Deck Graphic Art' },
  { id: 38, name: 'Lowbrow "Big Daddy" Roth Monster Art' },
  { id: 39, name: 'Garbage Pail Kids Parody Art' },
  { id: 40, name: 'Action Figure Packaging Art' },

  // --- Punk & DIY Aesthetics ---
  { id: 41, name: 'Ransom Note Cutout Lettering' },
  { id: 42, name: 'Distressed Photocopy Zine Texture' },
  { id: 43, name: 'Anarcho-Punk Stencil Graphic' },
  { id: 44, name: 'Chaotic Gig Flyer Collage' },
  { id: 45, name: 'Silkscreen Print Misalignment' },
  { id: 46, name: 'Torn Wheatpaste Poster Layers' },
  { id: 47, name: 'Safety Pin & Stud Aesthetic' },
  { id: 48, name: 'Hand-Scrawled Manifesto Text' },
  { id: 49, name: 'D-Beat/Raw Punk Record Cover' },
  { id: 50, name: 'DIY Sewn-On Patches Look' },
  { id: 51, name: 'Smeared Ink & Fingerprints' },
  { id: 52, name: 'Lettraset Transfer Lettering' },
  { id: 53, name: 'Hardcore Punk Band Photo aesthetic' },
  { id: 54, name: 'Riot Grrrl Cut-and-Paste Zine' },
  { id: 55, name: 'Duct Tape & Gaffer Tape aesthetic' },
  { id: 56, name: 'Marker Pen Tag on a surface' },
  { id: 57, name: 'Bleached & Splattered Fabric' },
  { id: 58, name: 'Rough Woodcut Print' },
  { id: 59, name: 'Anti-Art/Dada Collage' },
  { id: 60, name: 'Mimed Document / Redacted Text' },

  // --- Goth & Dark Aesthetics ---
  { id: 61, name: 'Victorian Mourning Portrait' },
  { id: 62, name: 'Post-Punk Minimalist Album Art' },
  { id: 63, name: 'Illegible Black Metal Logo' },
  { id: 64, name: 'Gothic Architectural Tracery' },
  { id: 65, name: 'Witch House Glitch Iconography' },
  { id: 66, name: 'Corpse Paint Aesthetic' },
  { id: 67, name: 'Medical Fetish/Latex Sheen' },
  { id: 68, name: 'Taxidermy Diorama' },
  { id: 69, name: 'Memento Mori Still Life' },
  { id: 70, name: 'Daguerreotype Photo Effect' },
  { id: 71, name: '4AD Records Ethereal Album Art' },
  { id: 72, name: 'Dark Ambient Soundscape visuals' },
  { id: 73, name: 'Cemetery Statuary Photography' },
  { id: 74, name: 'Cobweb-Covered & Decayed' },
  { id: 75, name: 'Film Noir High Contrast Lighting' },
  { id: 76, name: 'Expressionist Film Set (Caligari)' },
  { id: 77, name: 'Vampire Masquerade aesthetic' },
  { id: 78, name: 'Dried & Pressed Flowers' },
  { id: 79, name: 'Antique Medical Equipment' },
  { id: 80, name: 'Tarot Card Illustration' },

  // --- Hip Hop & Street Art Styles ---
  { id: 81, name: 'Wildstyle Graffiti Piece' },
  { id: 82, name: 'Bubble Letter Throw-Up' },
  { id: 83, name: 'Pen & Pixel Bling Album Cover' },
  { id: 84, name: 'Sticker Bomb Collage' },
  { id: 85, name: 'Hypebeast Logo Flip' },
  { id: 86, name: '90s Mixtape Cover Graphics' },
  { id: 87, name: 'Lowrider Airbrush Art' },
  { id: 88, name: 'Golden Age Hip Hop Fisheye Lens' },
  { id: 89, name: 'Underground Hip Hop Comic Style' },
  { id: 90, name: 'Soundcloud Rapper Face Tattoo Portrait' },
  { id: 91, name: 'Chopped & Screwed Album Art' },
  { id: 92, name: 'Graffiti Blackbook Sketch' },
  { id: 93, name: 'Street Art Mural (Photorealistic)' },
  { id: 94, name: 'Abstract Graffiti (Futura 2000)' },
  { id: 95, name: 'Memphis Rap Horror VHS Style' },
  { id: 96, name: 'Cash Money Records Album Art' },
  { id: 97, name: 'Rap-Tees style illustration' },
  { id: 98, name: 'Modern Trap Music Video Aesthetic' },
  { id: 99, name: 'Streetwear Tech Pack drawing' },
  { id: 100, name: 'G-Funk Album aesthetic' },

  // --- Digital, Glitch & Tech Styles ---
  { id: 101, name: 'Corrupted JPEG Artifacting' },
  { id: 102, name: 'CRT Monitor Phosphor Burn-in' },
  { id: 103, name: 'ASCII Art Rendering' },
  { id: 104, name: 'Vaporwave/Sadboy Aesthetic' },
  { id: 105, name: 'Vector-based Techwear Schematics' },
  { id: 106, name: 'Holographic Foil Sticker Effect' },
  { id: 107, name: 'Low-Poly PS1 Era 3D Model' },
  { id: 108, name: 'Y2K Cyber Tribal Graphics' },
  { id: 109, name: 'Fractal Noise/Generative Art' },
  { id: 110, name: 'Pixel Sorting Glitch Effect' },
  { id: 111, name: 'Windows 95 UI Aesthetic' },
  { id: 112, name: 'Geocities-era Web Design' },
  { id: 113, name: 'Seapunk Aesthetic' },
  { id: 114, name: 'Hacker "Green Screen" Terminal' },
  { id: 115, name: 'Post-Internet Art Collage' },
  { id: 116, name: 'Broken LCD Screen' },
  { id: 117, name: 'Wireframe 3D Model View' },
  { id: 118, name: 'Nightcore music video visuals' },
  { id: 119, name: 'Brutalist Web Design' },
  { id: 120, name: 'Surveillance Camera Footage' },

  // --- Film, Photo & Print Styles ---
  { id: 121, name: 'Lomography Light Leaks & Color Shifts' },
  { id: 122, name: 'Overexposed Flash Photography' },
  { id: 123, 'name': 'Found Footage Camcorder Look' },
  { id: 124, 'name': 'Giallo Film Poster Aesthetic' },
  { id: 125, 'name': 'Japanese Pinku Film Poster' },
  { id: 126, 'name': 'Infrared Security Camera View' },
  { id: 127, 'name': 'Bleach Bypass Film Processing' },
  { id: 128, 'name': 'Risograph Print Texture' },
  { id: 129, 'name': 'Halftone Comic Book Printing' },
  { id: 130, 'name': 'Cross-Processing Film Photography' },
  { id: 131, 'name': 'Wet Plate Collodion Photography' },
  { id: 132, 'name': 'Ken Burns Effect Documentary Photo' },
  { id: 133, 'name': 'Exploitation Film Poster (Grindhouse)' },
  { id: 134, 'name': 'Soviet Montage Film Style' },
  { id: 135, 'name': 'Troma Entertainment Movie Poster' },
  { id: 136, 'name': 'Cinemascope Widescreen' },
  { id: 137, 'name': 'Dutch Angle shot' },
  { id: 138, 'name': 'Lens Flare Overload (J.J. Abrams)' },
  { id: 139, 'name': 'Expired Polaroid Photo' },
  { id: 140, 'name': 'Double Exposure Photography' },

  // --- Texture & Material Styles ---
  { id: 141, 'name': 'Rusted & Corroded Metal' },
  { id: 142, 'name': 'Cracked Concrete Texture' },
  { id: 143, 'name': 'Peeling Paint on Wood' },
  { id: 144, 'name': 'Stained & Water-Damaged Paper' },
  { id: 145, 'name': 'Distressed Denim Fabric' },
  { id: 146, 'name': 'Carbon Fiber Weave' },
  { id: 147, 'name': 'Chainlink Fence Obstruction' },
  { id: 148, 'name': 'Barbed Wire Tangling' },
  { id: 149, 'name': 'Shattered Glass Fragments' },
  { id: 150, 'name': 'Xerox Copy Grain' },
  { id: 151, 'name': 'Rough Burlap Texture' },
  { id: 152, 'name': 'Torn Fishnet Fabric' },
  { id: 153, 'name': 'Cracked Leather Texture' },
  { id: 154, 'name': 'Charred & Burnt Material' },
  { id: 155, 'name': 'Bio-luminescent Fungus' },
  { id: 156, 'name': 'Oil Slick Iridescence' },
  { id: 157, 'name': 'Tar & Asphalt Texture' },
  { id: 158, 'name': 'Caution Tape Pattern' },
  { id: 159, 'name': 'Exposed Wires & Circuitry' },
  { id: 160, 'name': 'Melting Wax / Crayon Drip' },

  // --- Abstract & Conceptual Styles ---
  { id: 161, name: 'Sonic Waveform Visualization' },
  { id: 162, name: 'Psychological Inkblot Test (Rorschach)' },
  { id: 163, name: 'Action Painting (Jackson Pollock)' },
  { id: 164, name: 'Color Field Painting (Mark Rothko)' },
  { id: 165, name: 'Deconstructivist Architecture' },
  { id: 166, name: 'Geometric Abstraction (Malevich)' },
  { id: 167, name: 'Hard-Edge Painting' },
  { id: 168, name: 'Op Art (Bridget Riley)' },
  { id: 169, name: 'Scumbled Paint Technique' },
  { id: 170, name: 'Automatic Drawing (Surrealist)' },
  { id: 171, name: 'Frottage (Max Ernst)' },
  { id: 172, name: 'Asemic Writing' },
  { id: 173, name: 'Map Fold Lines' },
  { id: 174, name: 'Infographic/Diagram Style' },
  { id: 175, name: 'Heat Map / Thermal Imaging' },
  { id: 176, name: 'Kirlian Photography Aura' },
  { id: 177, name: 'Schlieren Photography' },
  { id: 178, name: 'Sonogram / Ultrasound Scan' },
  { id: 179, name: 'Seismic Wave Graph' },
  { id: 180, name: 'Topographical Map Contours' },

  // --- Horror & Grotesque Styles ---
  { id: 181, name: 'Body Horror (David Cronenberg)' },
  { id: 182, name: 'Found Footage Horror (Blair Witch)' },
  { id: 183, name: 'Cosmic Horror (Lovecraftian)' },
  { id: 184, name: 'Slasher Movie Poster (80s)' },
  { id: 185, name: 'Japanese Horror (J-Horror)' },
  { id: 186, name: 'Analog Horror (Local 58)' },
  { id: 187, name: 'Creepypasta visual aesthetic' },
  { id: 188, name: 'Uncanny Valley Android' },
  { id: 189, name: 'Disturbing Trail Cam Photo' },
  { id: 190, name: 'Backrooms Liminal Space' },
  { id: 191, name: 'Guillermo Del Toro Creature Design' },
  { id: 192, name: 'Hieronymus Bosch hellscape' },
  { id: 193, name: 'Silent Hill aesthetic (rust and fog)' },
  { id: 194, name: 'Resident Evil pre-rendered background' },
  { id: 195, name: 'Blood and Gore splatter' },
  { id: 196, name: 'Medical Gore/Surgical diagrams' },
  { id: 197, name: 'Taxidermy Abomination' },
  { id: 198, name: 'Visceral, fleshy textures' },
  { id: 199, name: 'Cannibal Corpse album art' },
  { id: 200, name: 'Joel-Peter Witkin photography style' },

  // --- Miscellaneous Edgy Styles ---
  { id: 201, name: 'Kustom Kulture Pinstriping' },
  { id: 202, name: 'Biker Gang colors/patches' },
  { id: 203, name: 'WW2 Era Military Propaganda Poster' },
  { id: 204, name: 'Cold War era espionage documents' },
  { id: 205, name: 'Stick and Poke Tattoo style' },
  { id: 206, name: 'Chicano Tattoo Lettering' },
  { id: 207, name: 'WPA-era Poster Art' },
  { id: 208, name: '1970s Sci-Fi Book Cover' },
  { id: 209, name: 'Pulp Fiction Magazine Cover' },
  { id: 210, name: 'Dieselpunk aesthetic' },
  { id: 211, name: 'Atompunk aesthetic' },
  { id: 212, name: 'Soviet Brutalist Monument' },
  { id: 213, name: 'Femme Fatale Portrait' },
  { id: 214, name: 'Hardboiled Detective Novel Cover' },
  { id: 215, name: 'Military Stencil Lettering' },
  { id: 216, name: 'Underground rave flyer (90s)' },
  { id: 217, name: 'BMX/Skate Zine photography' },
  { id: 218, name: 'Wrestling event poster (80s/90s)' },
  { id: 219, name: 'Postage Stamp design' },
  { id: 220, name: 'Classified Document Stamp' },
];
