
import type { FilterFX } from '../types';

export const FILTERS: FilterFX[] = [
    // --- Core & Basic Effects (1-20) ---
    { id: 1, description: 'High Contrast Black & White' },
    { id: 2, description: 'Heavy Film Grain' },
    { id: 3, description: 'VHS Static & Tracking Lines' },
    { id: 4, description: 'Chromatic Aberration' },
    { id: 5, description: 'CRT Scanlines' },
    { id: 6, description: 'Pixel Sorting Glitch' },
    { id: 7, description: 'Neon Duotone (Cyan & Magenta)' },
    { id: 8, description: 'Faded, Desaturated Colors' },
    { id: 9, description: 'Risograph Print Texture' },
    { id: 10, description: 'Infrared / Thermal Vision' },
    { id: 11, description: 'Holographic Shimmer' },
    { id: 12, description: 'Anamorphic Lens Flare' },
    { id: 13, description: 'Scratched Film Emulsion' },
    { id: 14, description: 'Halftone Dot Pattern (CMYK)' },
    { id: 15, description: 'Acid Trip Color Shift' },
    { id: 16, description: 'Light Leaks (Red & Orange)' },
    { id: 17, description: 'Anaglyph 3D (Red/Cyan)' },
    { id: 18, description: 'Datamosh Compression Artifacts' },
    { id: 19, description: 'X-Ray Negative' },
    { id: 20, description: 'Liquid Metal / Mercury Sheen' },
    
    // --- Analog & Vintage Photography (21-60) ---
    { id: 21, description: 'Expired Polaroid 600 Film' },
    { id: 22, description: 'Lomography Color Shift & Vignette' },
    { id: 23, description: 'Kodachrome Film (Rich Saturation)' },
    { id: 24, description: 'Technicolor (Three-Strip Process)' },
    { id: 25, description: 'Sepia Tone (Antique Photo)' },
    { id: 26, description: 'Cyanotype (Blueprint Effect)' },
    { id: 27, description: 'Daguerreotype (Silver Plate Look)' },
    { id: 28, description: 'Ambrotype (Wet Plate Collodion)' },
    { id: 29, description: 'Autochrome Lumière (Pointillist Color)' },
    { id: 30, description: 'Cross-Processed Slide Film' },
    { id: 31, description: 'Bleach Bypass (High Contrast, Low Saturation)' },
    { id: 32, description: 'Pushed Film (High Contrast & Grain)' },
    { id: 33, description: 'Faded Ektachrome Look' },
    { id: 34, description: '8mm Film Look (Dust & Scratches)' },
    { id: 35, description: 'Super 16mm Film Look (Heavy Grain)' },
    { id: 36, description: 'Lens Fungus / Haze' },
    { id: 37, description: 'Soft Focus / Dreamy Glow' },
    { id: 38, description: 'Petzval Lens Swirly Bokeh' },
    { id: 39, description: 'Pinhole Camera Distortion & Vignette' },
    { id: 40, description: 'Holga Plastic Lens Look' },
    { id: 41, description: 'Double Exposure Effect' },
    { id: 42, description: 'Solarization (Sabattier Effect)' },
    { id: 43, description: 'Reticulation (Film Cracking)' },
    { id: 44, description: 'Matte Print Finish' },
    { id: 45, description: 'Glossy Print Finish with Glare' },
    { id: 46, description: 'View-Master 3D Slide Effect' },
    { id: 47, description: 'Film Sprocket Holes Visible' },
    { id: 48, description: 'Chemical Stains on Emulsion' },
    { id: 49, description: 'Dusty Projector Light Beam' },
    { id: 50, description: 'Faded 1970s Photo Album Look' },
    { id: 51, description: 'Overexposed Flash Photography' },
    { id: 52, description: 'Redscale Film Effect' },
    { id: 53, description: 'Infrared Black & White (Wood Effect)' },
    { id: 54, description: 'Split Tone (Selenium & Gold)' },
    { id: 55, description: 'Hand-Tinted Black & White Photo' },
    { id: 56, description: 'Orton Effect (Glowing Overlay)' },
    { id: 57, description: 'Tilt-Shift Miniature Effect' },
    { id: 58, description: 'Wet Plate Drips & Imperfections' },
    { id: 59, description: 'Kirlian Photography Aura' },
    { id: 60, description: 'Schlieren Photography (Heat Haze)' },

    // --- Glitch & Digital Corruption (61-100) ---
    { id: 61, description: 'RGB Channel Splitting' },
    { id: 62, description: 'Vector Displacement Glitch' },
    { id: 63, description: 'Screen Tearing Effect' },
    { id: 64, description: 'Broken LCD Screen' },
    { id: 65, description: 'Digital Camo Pattern Overlay' },
    { id: 66, description: 'ASCII Art Conversion' },
    { id: 67, description: 'Bitcrushed / Low Bit Depth' },
    { id: 68, description: 'JPEG Compression Artifacts' },
    { id: 69, description: 'Stuck Pixel (Red, Green, or Blue)' },
    { id: 70, description: 'Buffer Overflow Artifacts' },
    { id: 71, description: 'Wireframe Overlay' },
    { id: 72, description: 'Low Poly / Faceted Look' },
    { id: 73, description: 'Terminal / Console Text Overlay' },
    { id: 74, description: 'Binary Code Overlay' },
    { id: 75, description: 'QR Code Pattern' },
    { id: 76, description: 'Image Dithering (Floyd-Steinberg)' },
    { id: 77, description: 'Pixelated / Mosaic Effect' },
    { id: 78, description: 'Heat Map / Thermal Imaging' },
    { id: 79, description: 'Sonar / Radar Sweep' },
    { id: 80, description: 'Night Vision Goggle View' },
    { id: 81, description: 'Corrupted File Data (Hex Edit)' },
    { id: 82, description: 'Y2K Cyber Aesthetic Overlay' },
    { id: 83, description: 'Vaporwave Pink & Cyan Glow' },
    { id: 84, description: 'Seapunk 3D Grids & Dolphins' },
    { id: 85, description: 'Witch House Occult Symbols' },
    { id: 86, description: 'Analog Video Signal Noise' },
    { id: 87, description: 'Frame Dropping / Stutter Effect' },
    { id: 88, description: 'Video Player UI Overlay' },
    { id: 89, description: 'Audio Waveform Visualization' },
    { id: 90, description: 'Spectrogram Overlay' },
    { id: 91, description: 'Windows 95 UI Aesthetic' },
    { id: 92, description: 'Mac OS 9 UI Aesthetic' },
    { id: 93, description: 'DVD Menu Screen' },
    { id: 94, description: 'Glitching Text Subtitles' },
    { id: 95, description: 'LED Screen Dot Matrix' },
    { id: 96, description: 'Matrix "Digital Rain"' },
    { id: 97, description: 'De-interlacing Artifacts' },
    { id: 98, description: 'Screen Burn-in / Ghosting' },
    { id: 99, description: 'Lossy GIF Compression' },
    { id: 100, description: 'FUI / Sci-Fi Interface Overlay' },

    // --- Cinematic & Color Grading (101-140) ---
    { id: 101, description: 'Teal & Orange Blockbuster Grade' },
    { id: 102, description: 'Matrix Green Tint' },
    { id: 103, description: 'Blade Runner (2049) Orange Haze' },
    { id: 104, description: 'Film Noir (Deep Shadows, High Contrast)' },
    { id: 105, description: 'Wes Anderson Symmetrical Pastel Palette' },
    { id: 106, description: 'Giallo Film (Saturated Reds & Blues)' },
    { id: 107, description: 'Mad Max Fury Road (High Saturation Orange)' },
    { id: 108, description: 'Amélie (Warm Greens & Reds)' },
    { id: 109, description: 'Sin City (B&W with Spot Color)' },
    { id: 110, description: 'Saving Private Ryan (Desaturated, Gritty)' },
    { id: 111, description: 'Day for Night (Blue Tint)' },
    { id: 112, description: 'Golden Hour Glow' },
    { id: 113, description: 'Letterbox (Cinematic Bars)' },
    { id: 114, description: 'Dutch Angle (Canted Frame)' },
    { id: 115, description: 'Rack Focus / Depth of Field Blur' },
    { id: 116, description: 'Motion Blur' },
    { id: 117, description: 'Fisheye Lens Distortion' },
    { id: 118, description: 'Split Diopter Effect' },
    { id: 119, description: 'Shaky Cam / Handheld Look' },
    { id: 120, description: 'Vertigo Effect (Dolly Zoom)' },
    { id: 121, description: 'Bloom / Light Diffusion' },
    { id: 122, description: 'Lens Smudges & Flares' },
    { id: 123, description: 'God Rays / Volumetric Lighting' },
    { id: 124, description: 'Vignette (Darkened Corners)' },
    { id: 125, description: 'Hard Light with Sharp Shadows' },
    { id: 126, description: 'Rim Lighting' },
    { id: 127, description: 'Subsurface Scattering (Skin Glow)' },
    { id: 128, description: 'Kurosawa-inspired B&W' },
    { id: 129, description: 'Tarkovsky-inspired Atmospheric Mist' },
    { id: 130, description: 'Lynchian Red Room' },
    { id: 131, description: 'Kubrick One-Point Perspective' },
    { id: 132, description: '80s Horror Movie Poster Grade' },
    { id: 133, description: '90s Action Movie Blue Tint' },
    { id: 134, description: 'Found Footage (Camcorder Look)' },
    { id: 135, description: 'Surveillance Camera (Low-Fi)' },
    { id: 136, description: 'Documentary Film Look' },
    { id: 137, description: 'IMAX Film Grain' },
    { id: 138, description: 'Color Gel on Lights' },
    { id: 139, description: 'Lens Breathing Effect' },
    { id: 140, description: 'Split Screen' },
    
    // --- Artistic & Textural (141-180) ---
    { id: 141, description: 'Watercolor Paper Texture' },
    { id: 142, description: 'Oil Painting Canvas Texture' },
    { id: 143, description: 'Charcoal Sketch on Toned Paper' },
    { id: 144, description: 'Cross-hatching Ink Lines' },
    { id: 145, description: 'Pointillism Effect' },
    { id: 146, description: 'Airbrush Sheen' },
    { id: 147, description: 'Woodcut / Linocut Print' },
    { id: 148, description: 'Etching / Engraving Lines' },
    { id: 149, description: 'Crumpled Paper Texture' },
    { id: 150, description: 'Stained Parchment' },
    { id: 151, description: 'Blueprint / Cyanotype Grid' },
    { id: 152, description: 'Architectural Drawing Style' },
    { id: 153, description: 'Manga Screentone' },
    { id: 154, description: 'Cut Paper Collage' },
    { id: 155, description: 'Rusted Metal Overlay' },
    { id: 156, description: 'Cracked Concrete Texture' },
    { id: 157, description: 'Peeling Paint' },
    { id: 158, description: 'Leather Texture' },
    { id: 159, description: 'Distressed Denim' },
    { id: 160, description: 'Stained Glass Window' },
    { id: 161, description: 'Mosaic Tile Effect' },
    { id: 162, description: 'Embroidery / Cross-Stitch' },
    { id: 163, description: 'Woven Fabric / Tapestry' },
    { id: 164, description: 'Brushed Aluminum Texture' },
    { id: 165, description: 'Gold Leaf Application' },
    { id: 166, 'description': 'Frosted Glass' },
    { id: 167, 'description': 'Reflective Water Caustics' },
    { id: 168, 'description': 'Bubble / Foam Texture' },
    { id: 169, 'description': 'Cracked Earth / Drought' },
    { id: 170, 'description': 'Lichen / Moss Growth' },
    { id: 171, 'description': 'Impasto Paint (Thick Strokes)' },
    { id: 172, 'description': 'Sumi-e Ink Wash' },
    { id: 173, 'description': 'Photocopy Drag / Smear' },
    { id: 174, 'description': 'Chalk Drawing on Pavement' },
    { id: 175, 'description': 'Torn Paper Edges' },
    { id: 176, 'description': 'Glitter / Sequins' },
    { id: 177, 'description': 'Fluorescent Marker Highlight' },
    { id: 178, 'description': 'Glow-in-the-Dark Phosphorescence' },
    { id: 179, 'description': 'Circuit Board Traces' },
    { id: 180, 'description': 'Liquid Crystal Display' },

    // --- Atmospheric & Environmental (181-220) ---
    { id: 181, 'description': 'Dense Fog / Mist' },
    { id: 182, 'description': 'Heavy Rain & Puddles' },
    { id: 183, 'description': 'Falling Snow / Blizzard' },
    { id: 184, 'description': 'Desert Sandstorm / Haze' },
    { id: 185, 'description': 'Underwater Distortion' },
    { id: 186, 'description': 'Smoky Room / Haze' },
    { id: 187, 'description': 'Floating Embers & Ash' },
    { id: 188, 'description': 'Swarm of Insects' },
    { id: 189, 'description': 'Falling Autumn Leaves' },
    { id: 190, 'description': 'Swirling Pollen / Dust Motes' },
    { id: 191, 'description': 'Lightning Storm Flashes' },
    { id: 192, 'description': 'Aurora Borealis Overlay' },
    { id: 193, 'description': 'Galaxy / Nebula Background' },
    { id: 194, 'description': 'Earthquake / Camera Shake' },
    { id: 195, 'description': 'Fire / Flames Overlay' },
    { id: 196, 'description': 'Explosion Debris' },
    { id: 197, 'description': 'Toxic Gas / Green Smoke' },
    { id: 198, 'description': 'Nuclear Fallout / Geiger Counter Ticks' },
    { id: 199, 'description': 'Gravity Distortion / Spacetime Warp' },
    { id: 200, 'description': 'Sonic Boom / Shockwave' },
    { id: 201, 'description': 'Post-Apocalyptic Dust & Ruin' },
    { id: 202, 'description': 'Bio-luminescent Forest Glow' },
    { id: 203, 'description': 'Cyberpunk City Rain & Neon Reflections' },
    { id: 204, 'description': 'Gothic Graveyard Mist' },
    { id: 205, 'description': 'Jungle Humidity / Lens Fog' },
    { id: 206, 'description': 'Misty Mountains' },
    { id: 207, 'description': 'Swamp Gas Bubbles' },
    { id: 208, 'description': 'Volcanic Ashfall' },
    { id: 209, 'description': 'Tornado / Debris Cyclone' },
    { id: 210, 'description': 'Solar Flare / Lens Glare' },
    { id: 211, 'description': 'Acid Rain Sizzle' },
    { id: 212, 'description': 'Wind-swept Look' },
    { id: 213, 'description': 'Time-lapse Cloud Movement' },
    { id: 214, 'description': 'Polluted City Smog' },
    { id: 215, 'description': 'Blood Splatter' },
    { id: 216, 'description': 'Zero-G Floating Debris' },
    { id: 217, 'description': 'Heavy Cobwebs' },
    { id: 218, 'description': 'Confetti / Streamers' },
    { id: 219, 'description': 'Bubbles' },
    { id: 220, 'description': 'Ectoplasm / Slime Trail' },
];
