import type { Pose } from '../types';

export const POSES: Pose[] = [
  // Street & Urban Poses
  { id: 1, description: 'Confident stance, hands in pockets of a hoodie' },
  { id: 2, description: 'Leaning against a graffiti-covered brick wall' },
  { id: 3, description: 'Mid-stride, walking towards the camera with purpose' },
  { id: 4, description: 'Sitting on a curb, looking up thoughtfully' },
  { id: 5, description: 'Adjusting sunglasses with one hand, looking cool' },
  { id: 6, description: 'Holding a skateboard over one shoulder' },
  { id: 7, description: 'Dynamic breakdance freeze on the pavement' },
  { id: 8, description: 'Hood up, looking down mysteriously, face obscured' },
  { id: 9, description: 'Jumping off a ledge, captured mid-air' },
  { id: 10, description: 'Crouched low to the ground, ready to spring up' },
  { id: 11, description: 'Checking a phone, illuminated by the screen\'s glow' },
  { id: 12, description: 'Looking over the shoulder with a challenging gaze' },
  { id: 13, description: 'Standing on a rooftop ledge overlooking a neon city' },
  { id: 14, description: 'A low-angle shot looking up, making the character imposing' },
  { id: 15, description: 'Tying the laces of a high-top sneaker' },
  { id: 16, description: 'Riding a skateboard, captured in a dynamic turn' },
  { id: 17, description: 'Spraying a graffiti tag on a wall' },
  { id: 18, description: 'Arms crossed with a defiant or confident expression' },
  { id: 19, description: 'Hanging off the side of a fire escape ladder' },
  { id: 20, description: 'Sitting backwards on a chair' },
  { id: 21, description: 'A candid laughing pose, head tilted back' },
  { id: 22, description: 'Putting on or taking off a pair of headphones' },
  { id: 23, description: 'Slumped against a chain-link fence' },
  { id: 24, description: 'Flipping a coin or token in the air' },
  { id: 25, description: 'Mid-air parkour jump between two surfaces' },
  
  // Attitude & Expressive Poses
  { id: 26, description: 'A powerful, wide-legged stance' },
  { id: 27, description: 'Shrugging with hands up in a "who knows?" gesture' },
  { id: 28, description: 'Pointing directly at the viewer' },
  { id: 29, description: 'Holding a hand up to shield from bright lights' },
  { id: 30, description: 'A quiet, contemplative pose, looking at the ground' },
  { id: 31, description: 'Blowing a bubble with bubblegum' },
  { id: 32, description: 'Adjusting the collar of a jacket' },
  { id: 33, description: 'A challenging stare, sizing up an opponent' },
  { id: 34, description: 'Holding a finger to the lips in a "shhh" gesture' },
  { id: 35, description: 'Running a hand through hair or fur on the head' },
  { id: 36, description: 'A relaxed, slouching posture' },
  { id: 37, description: 'Throwing a peace sign' },
  { id: 38, description: 'A hip-hop inspired pose, with one hand near the face' },
  { id: 39, description: 'Fist clenched, ready for a fight' },
  { id: 40, description: 'A cocky, one-eyebrow-raised expression' },
  { id: 41, description: 'Bouncing on the balls of the feet, full of energy' },
  { id: 42, description: 'A bored expression, leaning on one hand' },
  { id: 43, description: 'Hands clasped behind the head, relaxing' },
  { id: 44, description: 'In the middle of a frantic, energetic dance move' },
  { id: 45, description: 'A facepalm gesture of exasperation' },
  { id: 46, description: 'Wiping a tear away, in a moment of sadness' },
  { id: 47, description: 'Hugging knees to chest' },
  { id: 48, description: 'Offering a hand to the viewer, as if to help them up' },
  { id: 49, description: 'A menacing, predatory crouch' },
  { id: 50, description: 'Arms outstretched, embracing the city skyline' },

  // Action & Item Poses (from former traits)
  { id: 51, description: 'A hunchbacked posture' },
  { id: 52, description: 'Body is unnaturally contorted' },
  { id: 53, description: 'Body seems to defy gravity' },
  { id: 54, description: 'Holding a Dripping Spray Paint Can' },
  { id: 55, description: 'Holding a Katana with glowing edge' },
  { id: 56, description: 'Holding a rusty, crimson-stained cleaver' },
  { id: 57, description: 'Holding a large, crimson-stained axe' },
  { id: 58, description: 'Holding a skull with glowing eyes' },
  { id: 59, description: 'Wielding a large, menacing meat cleaver' },
  { id: 60, description: 'Holding a crimson-stained, serrated blade' },
  { id: 61, description: 'Wielding a heavy-duty rotary cutter' },
  { id: 62, description: 'Holding a glitching data-tablet' },
  { id: 63, description: 'Carrying an old-school boombox' },
  { id: 64, description: 'Wielding a massive, steampunk wrench' },
  { id: 65, description: 'Holding a futuristic laser rifle' },
  { id: 66, description: 'Posed with a microphone on a stand' },
  { id: 67, description: 'Wielding a crowbar' },
  { id: 68, description: 'Holding a crudely reinforced baseball bat' },
  { id: 69, description: 'About to throw a flaming bottle' },
  { id: 70, description: 'Holding a grotesque trophy head' },
  { id: 71, description: 'Reading from a book of ancient spells' },
  { id: 72, description: 'Gazing into a crystal ball' },
  { id: 73, description: 'Displaying a deck of tarot cards' },
  { id: 74, description: 'Holding a lit stick of dynamite' },
  { id: 75, description: 'Holding a single, black rose' },
  { id: 76, description: 'Holding a flickering lantern' },
  { id: 77, description: 'Wielding a scythe' },
  { id: 78, description: 'Wielding a glowing energy sword' },
  { id: 79, description: 'Clutching a small teddy bear' },
  { id: 80, description: 'Eating a half-eaten lollipop' },
  { id: 81, description: 'Holding a video game controller' },
  { id: 82, description: 'Posed with a set of DJ turntables' },
  { id: 83, description: 'Holding a medical syringe' },
  { id: 84, description: 'Drinking a bottle of mysterious potion' },
  { id: 85, description: 'Playing a flute made of bone' },
  { id: 86, description: 'Bracing behind a riot shield' },
  { id: 87, description: 'Spraying a fire extinguisher' },
  { id: 88, description: 'Swinging a sledgehammer' },
  { id: 89, description: 'Wielding a cattle prod' },
  { id: 90, description: 'Casting a fishing rod' },
  { id: 91, description: 'Wielding a whip of articulated bones' },
  { id: 92, description: 'Holding a magical staff' },
  { id: 93, description: 'Walking a plague rat on a leash' },
  { id: 94, description: 'Levitating slightly off the ground' },
  { id: 95, description: 'Speaking in tongues (visible glyphs)' },
  { id: 96, description: 'In the middle of summoning a small demon' },
  { id: 97, description: 'Casting a dark spell' },
  { id: 98, description: 'Body is possessed, contorting unnaturally' },
  { id: 99, description: 'Whispering dark secrets' },
  { id: 100, description: 'A zombie-like, shambling walk' },
  { id: 101, description: 'A ghoul, hunched over the remnants of a feast' },
  { id: 102, description: 'A jiangshi (hopping vampire) pose' },
  { id: 103, description: 'A banshee, wailing with hands to face' },
];