import type { Saying } from '../types';

export const SAYINGS: Saying[] = [
  { id: 1, text: 'Stay Weird' },
  { id: 2, text: 'Create & Destroy' },
  { id: 3, text: 'Vandal Life' },
  { id: 4, text: 'Goth Hop' },
  { id: 5, text: 'No Sleep' },
  { id: 6, text: 'Stay Hungry' },
  { id: 7, text: 'Trust No One' },
  { id: 8, text: 'Anti Social' },
  { id: 9, text: 'Lost Soul' },
  { id: 10, text: 'Respect The Drip' },
  { id: 11, text: 'Legends Never Die' },
  { id: 12, text: 'Do Not Cross' },
  { id: 13, text: 'Too Broke For Supreme' },
  { id: 14, text: 'Void' },
  { id: 15, text: 'Error 404' },
  { id: 16, text: 'Offline' },
  { id: 17, text: 'Loading...' },
  { id: 18, text: 'Sad But Rad' },
  { id: 19, text: 'Savage' },
  { id: 20, text: 'Hustle Hard' },
  { id: 21, text: 'Good Vibes Only' },
  { id: 22, text: 'Stay Gold' },
  { id: 23, text: 'Dream Chaser' },
  { id: 24, text: 'Never Settle' },
  { id: 25, text: 'Ride or Die' },
  { id: 26, text: 'No Apologies' },
  { id: 27, text: 'Unbreakable' },
  { id: 28, text: 'Beast Mode' },
  { id: 29, text: 'Fearless' },
  { id: 30, text: 'Chaos' },
  { id: 31, text: 'Royalty' },
  { id: 32, text: 'Loyalty' },
  { id: 33, text: 'Family First' },
  { id: 34, text: 'Day One' },
  { id: 35, text: 'Blessed' },
  { id: 36, text: 'Cursed' },
  { id: 37, text: 'Limited Edition' },
  { id: 38, text: 'Rare' },
  { id: 39, text: 'OG' },
  { id: 40, text: 'Hypebeast' },
  { id: 41, text: 'Out of Stock' },
  { id: 42, text: 'Sold Out' },
  { id: 43, text: 'Player One' },
  { id: 44, text: 'Game Over' },
  { id: 45, text: 'High Score' },
  { id: 46, text: 'Level Up' },
  { id: 47, text: 'Respawn' },
  { id: 48, text: 'Glitch' },
  { id: 49, text: 'Pixelated' },
  { id: 50, text: 'Analog' },
  { id: 51, text: 'Digital' },
  { id: 52, text: 'System Failure' },
  { id: 53, text: 'Reboot' },
  { id: 54, text: 'No Future' },
  { id: 55, text: 'Cyberpunk' },
  { id: 56, text: 'Dystopia' },
  { id: 57, text: 'Utopia' },
  { id: 58, text: 'Paradox' },
  { id: 59, text: 'Anarchy' },
  { id: 60, text: 'Rebel' },
  { id: 61, text: 'Riot' },
  { id: 62, text: 'Revolution' },
  { id: 63, text: 'Freedom' },
  { id: 64, text: 'Justice' },
  { id: 65, text: 'Truth' },
  { id: 66, text: 'Silence' },
  { id: 67, text: 'Noise' },
  { id: 68, text: 'Static' },
  { id: 69, text: 'Frequency' },
  { id: 70, text: 'Vibration' },
  { id: 71, text: 'Energy' },
  { id: 72, text: 'Momentum' },
  { id: 73, text: 'Velocity' },
  { id: 74, text: 'Gravity' },
  { id: 75, text: 'Orbit' },
  { id: 76, text: 'Galaxy' },
  { id: 77, text: 'Cosmic' },
  { id: 78, text: 'Stardust' },
  { id: 79, text: 'Nebula' },
  { id: 80, text: 'Eclipse' },
  { id: 81, text: 'Lunar' },
  { id: 82, text: 'Solar' },
  { id: 83, text: 'Midnight' },
  { id: 84, text: 'Dawn' },
  { id: 85, text: 'Dusk' },
  { id: 86, text: 'Twilight' },
  { id: 87, text: 'After Dark' },
  { id: 88, text: 'Night Owl' },
  { id: 89, text: 'Insomniac' },
  { id: 90, text: 'Lucid Dream' },
  { id: 91, text: 'Nightmare' },
  { id: 92, text: 'Fever Dream' },
  { id: 93, text: 'Hallucination' },
  { id: 94, text: 'Psychedelic' },
  { id: 95, text: 'Trippy' },
  { id: 96, text: 'Mind Control' },
  { id: 97, text: 'Brainwashed' },
  { id: 98, text: 'Paranoid' },
  { id: 99, text: 'Delusional' },
  { id: 100, text: 'Sanity is Overrated' },
  { id: 101, text: 'Normal is Boring' },
  { id: 102, text: 'Be Different' },
  { id: 103, text: 'Think Outside the Box' },
  { id: 104, text: 'Question Everything' },
  { id: 105, text: 'The Answer is No' },
  { id: 106, text: 'I Said What I Said' },
  { id: 107, text: 'Deal With It' },
  { id: 108, text: 'No Regrets' },
  { id: 109, text: 'Zero Flux Given' },
  { id: 110, text: 'Unimpressed' },
  { id: 111, text: 'Over It' },
  { id: 112, text: 'Whatever' },
  { id: 113, text: 'As If' },
  { id: 114, text: 'Bruh' },
  { id: 115, text: 'Mood' },
  { id: 116, text: 'Vibe' },
  { id: 117, text: 'Lit' },
  { id: 118, text: 'Dope' },
  { id: 119, text: 'Fresh' },
  { id: 120, text: 'Gucci' },
  { id: 121, text: 'Flex' },
  { id: 122, text: 'G.O.A.T.' },
  { id: 123, text: 'King' },
  { id: 124, text: 'Queen' },
  { id: 125, text: 'Icon' },
  { id: 126, text: 'Legend' },
  { id: 127, text: 'Myth' },
  { id: 128, text: 'Ghost' },
  { id: 129, text: 'Demon' },
  { id: 130, text: 'Angel' },
  { id: 131, text: 'Sinner' },
  { id: 132, text: 'Saint' },
  { id: 133, text: 'Villain' },
  { id: 134, text: 'Hero' },
  { id: 135, text: 'Anti-Hero' },
  { id: 136, text: 'Main Character' },
  { id: 137, text: 'Side Quest' },
  { id: 138, text: 'NPC' },
  { id: 139, text: 'Final Boss' },
  { id: 140, text: 'Tutorial' },
  { id: 141, text: 'Easy Mode' },
  { id: 142, text: 'Hard Mode' },
  { id: 143, text: 'Nightmare Mode' },
  { id: 144, text: 'God Mode' },
  { id: 145, text: 'AFK' },
  { id: 146, text: 'GG' },
  { id: 147, text: 'Noob' },
  { id: 148, text: 'Pro' },
  { id: 149, text: 'Hacker' },
  { id: 150, text: 'Cheat Code' },
  { id: 151, text: 'Easter Egg' },
  { id: 152, text: 'Secret Level' },
  { id: 153, text: 'Bonus Round' },
  { id: 154, text: 'Extra Life' },
  { id: 155, text: 'Continue?' },
  { id: 156, text: 'Insert Coin' },
  { id: 157, text: 'Press Start' },
  { id: 158, text: 'Select Your Player' },
  { id: 159, text: 'Choose Your Fighter' },
  { id: 160, text: 'FINISH HIM' },
  { id: 161, text: 'Flawless Victory' },
  { id: 162, text: 'K.O.' },
  { id: 163, text: 'Combo Breaker' },
  { id: 164, text: 'M-M-M-MONSTER DEFEAT' },
  { id: 165, text: 'Precision Shot' },
  { id: 166, text: 'Owned' },
  { id: 167, text: 'Rekt' },
  { id: 168, text: 'Salty' },
  { id: 169, text: 'Toxic' },
  { id: 170, text: 'Canceled' },
  { id: 171, text: 'Woke' },
  { id: 172, text: 'Based' },
  { id: 173, text: 'Redpilled' },
  { id: 174, text: 'Cringe' },
  { id: 175, text: 'Simp' },
  { id: 176, text: 'Chad' },
  { id: 177, text: 'Karen' },
  { id: 178, text: 'Boomer' },
  { id: 179, text: 'Zoomer' },
  { id: 180, text: 'Millennial' },
  { id: 181, text: 'Gen X' },
  { id: 182, text: 'OK' },
  { id: 183, text: 'LOL' },
  { id: 184, text: 'LMAO' },
  { id: 185, text: 'ROFL' },
  { id: 186, text: 'YOLO' },
  { id: 187, text: 'FOMO' },
  { id: 188, text: 'IYKYK' },
  { id: 189, text: 'Bet' },
  { id: 190, text: 'Cap' },
  { id: 191, text: 'No Cap' },
  { id: 192, text: 'Sheesh' },
  { id: 193, text: 'Finna' },
  { id: 194, text: 'Glow Up' },
  { id: 195, text: 'Drip' },
  { id: 196, text: 'Sauce' },
  { id: 197, text: 'Swag' },
  { id: 198, text: 'Fire' },
  { id: 199, text: 'Icy' },
  { id: 200, text: 'Wavy' },
  
  // --- Hip Hop, Goth, Streetwear, Sarcastic (Batch 1) ---
  { id: 201, text: 'The World Is Yours' },
  { id: 202, text: 'Dead Inside' },
  { id: 203, text: 'Emotionally Unavailable' },
  { id: 204, text: 'C.R.E.A.M.' },
  { id: 205, text: 'All Black Everything' },
  { id: 206, text: 'I\'m Not For Everyone' },
  { id: 207, text: 'Started From The Bottom' },
  { id: 208, text: 'My Soul is Black' },
  { id: 209, text: 'For The Culture' },
  { id: 210, text: 'Sounds Like a You Problem' },
  { id: 211, text: 'It Was All A Dream' },
  { id: 212, text: 'Welcome To The Darkness' },
  { id: 213, text: 'Grail Acquired' },
  { id: 214, text: 'I\'m Fine. It\'s Fine. Everything is Fine.' },
  { id: 215, text: 'Protect Ya Neck' },
  { id: 216, text: 'Love Will Tear Us Apart' },
  { id: 217, text: 'Fresh to Death' },
  { id: 218, text: 'Hold On, Let Me Overthink This' },
  { id: 219, text: 'Straight Outta Compton' },
  { id: 220, text: 'Beauty in Decay' },
  { id: 221, text: 'Deadstock' },
  { id: 222, text: 'I\'d Agree With You, But Then We\'d Both Be Wrong' },
  { id: 223, text: 'Mo Money Mo Problems' },
  { id: 224, text: 'Dancing With My Demons' },
  { id: 225, text: 'Street Certified' },
  { id: 226, text: 'Not Today, Satan' },
  { id: 227, text: 'God\'s Plan' },
  { id: 228, text: 'Poetry & Poison' },
  { id: 229, text: 'Respect the Fit' },
  { id: 230, text: 'Powered by Caffeine and Sarcasm' },
  { id: 231, text: 'Stay Humble' },
  { id: 232, text: 'Long Live The Night' },
  { id: 233, text: 'Cop or Drop?' },
  { id: 234, text: 'I Need a Hug...e Amount of Money' },
  { id: 235, text: 'All Eyez On Me' },
  { id: 236, text: 'Memento Mori' },
  { id: 237, text: 'The Plug' },
  { id: 238, text: 'My Ancestors Told Me You\'re an Idiot' },
  { id: 239, text: 'No Limit' },
  { id: 240, text: 'Sad Songs, Dark Hearts' },
  { id: 241, text: 'Stay Fly' },
  { id: 242, text: 'I Put The Pro in Procrastinate' },
  { id: 243, text: 'Real Gs Move in Silence' },
  { id: 244, text: 'Goth is the New Black' },
  { id: 245, text: 'W.T.A. (Wu-Tang Again?)' },
  { id: 246, text: 'Sorry, I\'m Late. I Didn\'t Want to Come.' },
  { id: 247, text: 'The Message' },
  { id: 248, text: 'More Issues Than Vogue' },
  { id: 249, text: 'Box Logo' },
  { id: 250, text: 'I\'m Allergic to Mornings' },
  { id: 251, text: 'Nuthin\' But A G Thang' },
  { id: 252, text: 'This is My Happy Face' },
  { id: 253, text: 'If The Shoe Fits...' },
  { id: 254, text: 'Sarcasm is My Love Language' },
  { id: 255, text: 'The Miseducation' },
  { id: 256, text: 'Spooky All Year' },
  { id: 257, text: 'IYKYK' },
  { id: 258, text: 'I Came. I Saw. I Made it Awkward.' },
  { id: 259, text: 'Illmatic' },
  { id: 260, text: 'I Have the Soul of a Cat' },
  { id: 261, text: 'Collab' },
  { id: 262, text: 'I Do a Thing Called What I Want' },
  { id: 263, text: 'Fear of a Black Planet' },
  { id: 264, text: 'Cemetery Chic' },
  { id: 265, text: 'Aesthetic' },
  { id: 266, text: 'I\'m Not Great at Advice. Can I Interest You in a Sarcastic Comment?' },
  { id: 267, text: 'Ready to Die' },
  { id: 268, text: 'Darkness is My Only Friend' },
  { id: 269, text: 'From the Block' },
  { id: 270, text: 'Ew, People' },
  { id: 271, text: 'DAMN.' },
  { id: 272, text: 'I Like My Coffee Black, Like My Soul' },
  { id: 273, text: 'Stay Cozy' },
  { id: 274, text: 'Go Away' },
  { id: 275, text: 'To Pimp A Butterfly' },
  { id: 276, text: 'Our Lady of Sorrows' },
  { id: 277, text: 'One of a Kind' },
  { id: 278, text: 'Chaos, but make it cute' },
  { id: 279, text: 'Good Kid, M.A.A.D City' },
  { id: 280, text: 'Misery Loves Company' },
  { id: 281, text: 'On My Grind' },
  { id: 282, text: 'I\'m Silently Correcting Your Grammar' },
  { id: 283, text: 'The Chronic' },
  { id: 284, text: 'I Listen to Bands That Don\'t Exist Anymore' },
  { id: 285, text: 'Off The Wall' },
  { id: 286, text: 'Tact is for People Who Aren\'t Witty Enough to be Sarcastic' },
  { id: 287, text: 'By All Means Necessary' },
  { id: 288, text: 'Tragic & Magic' },
  { id: 289, text: 'Got Sole?' },
  { id: 290, text: 'My Dog is My Co-pilot' },
  { id: 291, text: 'Poetic Justice' },
  { id: 292, text: 'Death Before Decaf' },
  { id: 293, text: 'Skate or Die' },
  { id: 294, text: 'I Have No Idea What I\'m Doing' },
  { id: 295, text: 'Juicy' },
  { id: 296, text: 'Haunted' },
  { id: 297, text: 'Urban Explorer' },
  { id: 298, text: 'Adulting is a Myth' },
  { id: 299, text: 'Hypnotize' },
  { id: 300, text: 'Gloomy' },
  { id: 301, text: 'Bodega Cat' },
  { id: 302, text: 'I Run on Anxiety and Iced Coffee' },
  { id: 303, text: 'The Blueprint' },
  { id: 304, text: 'Bats & Cats' },
  { id: 305, text: 'No Photos Please' },
  { id: 306, text: 'My Brain Has Too Many Tabs Open' },
  { id: 307, text: 'Rapper\'s Delight' },
  { id: 308, text: 'Embrace the Shadows' },
  { id: 309, text: 'Still Fresh' },
  { id: 310, text: 'Professional Overthinker' },
  { id: 311, text: 'All I Do Is Win' },
  { id: 312, text: 'Every Day is Halloween' },
  { id: 313, text: 'Certified Fresh' },
  { id: 314, text: 'Maybe She\'s Born With It, Maybe It\'s Caffeine' },
  { id: 315, text: 'Hard Knock Life' },
  { id: 316, text: 'I\'m the Ghost with the Most' },
  { id: 317, text: 'Checks Over Stripes' },
  { id: 318, text: 'I Whisper WTF to Myself, A Lot' },
  { id: 319, text: 'Can\'t Stop, Won\'t Stop' },
  { id: 320, text: 'Pretty on the Outside, Evil on the Inside' },
  { id: 321, text: 'Concrete Jungle' },
  { id: 322, text: 'It\'s a Vibe' },
  { id: 323, text: 'Money Trees' },
  { id: 324, text: 'We Are The Weirdos, Mister' },
  { id: 325, text: 'Born & Raised' },
  { id: 326, text: 'Shhh... I\'m Busy' },
  { id: 327, text: 'Boss Life' },
  { id: 328, text: 'Death Moth' },
  { id: 329, text: 'Quality Goods' },
  { id: 330, text: 'Namaste Away From Me' },
  { id: 331, text: 'I Got 99 Problems' },
  { id: 332, text: 'Strange & Unusual' },
  { id: 333, text: 'Est. MCMXC' },
  { id: 334, text: 'I Need More Space' },
  { id: 335, text: 'Hypnotiq' },
  { id: 336, text: 'The Cure Fanclub' },
  { id: 337, text: 'Never Sleep' },
  { id: 338, text: 'You Read My Shirt. That\'s Enough Social Interaction.' },
  { id: 339, text: 'Don\'t Believe The Hype' },
  { id: 340, text: 'Siouxsie is my Spirit Animal' },
  { id: 341, text: 'Original Recipe' },
  { id: 342, text: 'I\'m Not Angry, This Is Just My Face' },
  { id: 343, text: 'Stakes is High' },
  { id: 344, text: 'Coven' },
  { id: 345, text: 'Keep It Real' },
  { id: 346, text: 'Currently Avoiding Responsibilities' },
  { id: 347, text: 'It Takes A Nation of Millions...' },
  { id: 348, text: 'Bauhaus is Undead' },
  { id: 349, text: 'No Gods, No Masters' },
  { id: 350, text: 'I Have the Patience of a Saint... Just Kidding' },
  { id: 351, text: 'Paid in Full' },
  { id: 352, text: 'Witchcraft & Wine' },
  { id: 353, text: 'Too Fast To Live' },
  { id: 354, text: 'Error: Does Not Compute' },
  { id: 355, text: 'Grindin\'' },
  { id: 356, text: 'Full Moon Energy' },
  { id: 357, text: 'Too Broke For This' },
  { id: 358, text: 'Why be moody when you can shake yo booty?' },
  { id: 359, text: 'Stillmatic' },
  { id: 360, text: 'Local Cryptid' },
  { id: 361, text: 'Self Made' },
  { id: 362, text: 'I\'m Not Old, I\'m a Classic' },
  { id: 363, text: 'Roc-A-Fella' },
  { id: 364, text: 'Living Dead Girl' },
  { id: 365, text: 'Anti-You' },
  { id: 366, text: 'Be Nice to Me, I\'m on My Last Brain Cell' },
  { id: 367, text: 'Public Enemy No. 1' },
  { id: 368, text: 'I put the "fun" in funeral' },
  { id: 369, text: 'The Breaks' },
  { id: 370, text: 'Please Don\'t Talk To Me' },
  { id: 371, text: 'Bad Boy For Life' },
  { id: 372, text: 'Ouija Board Operator' },
  { id: 373, text: 'Do Not Read The Next Sentence' },
  { id: 374, text: 'You Are a Clever Little Fucker' },
  { id: 375, text: 'In My Zone' },
  { id: 376, text: 'Creature of the Night' },
  { id: 377, text: 'If Found, Return to the 90s' },
  { id: 378, text: 'I\'m a Delicate Fucking Flower' },
  { id: 379, text: 'Cash Money Records' },
  { id: 380, text: 'Sarcastic, But Sweet' },
  { id: 381, text: 'Art Official' },
  { id: 382, text: 'Of Course I Talk to Myself. Sometimes I Need Expert Advice.' },
  { id: 383, text: 'The Low End Theory' },
  { id: 384, text: 'Goth Before It Was Cool' },
  { id: 385, text: 'Probably Hungry' },
  { id: 386, text: 'That\'s a Horrible Idea. What Time?' },
  { id: 387, text: 'Still Tippin\'' },
  { id: 388, text: 'Gloomy Days & Starry Nights' },
  { id: 389, text: 'Eat The Rich' },
  { id: 390, text: 'I\'m not always sarcastic. Sometimes I\'m sleeping.' },
  { id: 391, text: 'Def Jam' },
  { id: 392, text: 'Black No. 1' },
  { id: 393, text: 'Too Glam To Give A Damn' },
  { id: 394, text: 'I Can\'t Adult Today' },
  { id: 395, text: 'Ruff Ryders' },
  { id: 396, text: 'Melancholy Baby' },
  { id: 397, text: 'Anti-Everything' },
  { id: 398, text: 'My Patronus is a Dementor' },
  { id: 399, text: 'Death Row Records' },
  { id: 400, text: 'Stay Creepy' },

  // --- Hip Hop, Goth, Streetwear, Sarcastic (Batch 2) ---
  { id: 401, text: 'Another One' },
  { id: 402, text: 'Bathed in Moonlight' },
  { id: 403, text: 'My Spirit Animal is a Grumpy Cat' },
  { id: 404, text: 'We The Best' },
  { id: 405, text: 'Ashes to Ashes' },
  { id: 406, text: 'Grail Status' },
  { id: 407, text: 'Life is Soup and I am a Fork' },
  { id: 408, text: 'Drop it Like It\'s Hot' },
  { id: 409, text: 'Beautifully Broken' },
  { id: 410, text: 'Never Not Creating' },
  { id: 411, text: 'I\'m Not Insulting You, I\'m Describing You' },
  { id: 412, text: 'Word Is Bond' },
  { id: 413, text: 'Nocturnal By Nature' },
  { id: 414, text: 'Worn To Be Seen' },
  { id: 415, text: 'You Sound Better With Your Mouth Closed' },
  { id: 416, text: 'Shook Ones' },
  { id: 417, text: 'Danse Macabre' },
  { id: 418, text: 'Sample - Not For Resale' },
  { id: 419, text: 'I\'m Busy, Can I Ignore You Later?' },
  { id: 420, text: 'Straight Cash, Homie' },
  { id: 421, text: 'Gloom & Doom' },
  { id: 422, text: 'DIY or Die' },
  { id: 423, text: 'I\'m on Energy-Saving Mode' },
  { id: 424, text: 'Can I Kick It? Yes I Can!' },
  { id: 425, text: 'Elegant Decay' },
  { id: 426, text: 'The Ten' },
  { id: 427, text: 'My Silence is Not an Absence of Opinion' },
  { id: 428, text: 'No Church in the Wild' },
  { id: 429, text: 'Batcave Resident' },
  { id: 430, text: 'Friends & Family Exclusive' },
  { id: 431, text: 'I\'m Multitasking: I Can Listen, Ignore, and Forget' },
  { id: 432, text: 'Forgot About Dre' },
  { id: 433, text: 'Lost in the Echo' },
  { id: 434, text: 'Cook Group Confidential' },
  { id: 435, text: 'I\'m Sorry for What I Said When I Was Hungry' },
  { id: 436, text: 'The Marathon Continues' },
  { id: 437, text: 'Under a Funeral Moon' },
  { id: 438, text: 'Support Your Local Skateshop' },
  { id: 439, text: 'I\'m Not Bossy, I Just Have Better Ideas' },
  { id: 440, text: 'It\'s All Good' },
  { id: 441, text: 'Vampire Kiss' },
  { id: 442, text: 'Thrasher' },
  { id: 443, text: 'I Speak Fluent Sarcasm' },
  { id: 444, text: 'Run The Jewels' },
  { id: 445, text: 'Gothic Romance' },
  { id: 446, text: 'If it ain\'t XO then it gotta go' },
  { id: 447, text: 'Don\'t Test My Inner Gangster' },
  { id: 448, text: 'Poison Ivy' },
  { id: 449, text: 'This Charming Man' },
  { id: 450, text: 'I\'m not always right, but I\'m never wrong' },
  { id: 451, text: 'It\'s a GOOD Day to have a GOOD day' },
  { id: 452, text: 'I Can and I Will. Watch Me.' },
  { id: 453, text: 'Humble with a hint of Kanye' },
  { id: 454, text: 'Too blessed to be stressed' },
  { id: 455, text: 'There is no "we" in fries' },
  { id: 456, text: 'Sicker than your average' },
  { id: 457, text: 'A Little Bit Dramatic' },
  { id: 458, text: 'I need a six-month vacation, twice a year' },
  { id: 459, text: 'Catch flights, not feelings' },
  { id: 460, text: 'Be a warrior, not a worrier' },
  { id: 461, text: 'I got a good heart but this mouth' },
  { id: 462, text: 'If you were a vegetable, you\'d be a cutecumber' },
  { id: 463, text: 'Not all who wander are lost' },
  { id: 464, text: 'Let your faith be bigger than your fear' },
  { id: 465, text: 'The sun is a daily reminder that we too can rise again' },
  { id: 466, text: 'The comeback is always stronger than the setback' },
  { id: 467, text: 'Your vibe attracts your tribe' },
  { id: 468, text: 'Throw sass around like confetti' },
  { id: 469, text: 'I\'m not weird, I\'m a limited edition' },
  { id: 470, text: 'I followed my heart, it led me to the fridge' },
  { id: 471, text: 'Be the reason someone smiles today' },
  { id: 472, text: 'In a world where you can be anything, be kind' },
  { id: 473, text: 'Don\'t be a lady, be a legend' },
  { id: 474, text: 'She turned her can\'ts into cans and her dreams into plans' },
  { id: 475, text: 'Life is short. Buy the shoes.' },
  { id: 476, text: 'I have a therapist; her name is music' },
  { id: 477, text: 'You can\'t buy happiness, but you can buy pizza' },
  { id: 478, text: 'Stay close to people who feel like sunlight' },
  { id: 479, text: 'A sass a day keeps the basics away' },
  { id: 480, text: 'I can\'t hear you over the sound of my freedom' },
  { id: 481, text: 'I\'m not a player, I\'m the game' },
  { id: 482, text: 'I\'m not responsible for what my face does when you talk' },
  { id: 483, text: 'I\'m not short, I\'m fun-sized' },
  { id: 484, text: 'I\'m not a morning person' },
  { id: 485, text: 'I\'m not arguing, I\'m explaining why I\'m right' },
  { id: 486, text: 'I\'m not saying I\'m Batman, but we\'ve never been seen in the same room' },
  { id: 487, text: 'I\'m not a complete idiot, some parts are missing' },
  { id: 488, text: 'I\'m not a snack, I\'m a whole meal' },
  { id: 489, text: 'I\'m not a doctor, but I\'ll take a look' },
  { id: 490, text: 'I\'m not a photographer, but I can picture us together' },
  { id: 491, text: 'I\'m not a weatherman, but you can expect a few inches tonight' },
  { id: 492, text: 'I\'m not a magician, but I can make your clothes disappear' },
  { id: 493, text: 'I\'m not a baker, but I can make your buns rise' },
  { id: 494, text: 'I\'m not a gardener, but I can make your flower bloom' },
  { id: 495, text: 'I\'m not a painter, but I can paint a smile on your face' },
  { id: 496, text: 'I\'m not a writer, but I can write our love story' },
  { id: 497, text: 'I\'m not a musician, but I can make your heart sing' },
  { id: 498, text: 'I\'m not a poet, but I can make you rhyme' },
  { id: 499, text: 'I\'m not a chef, but I can cook up some love' },
  { id: 500, text: 'I\'m not a comedian, but I can make you laugh' },
  { id: 501, text: 'I\'m not a dancer, but I can make your heart dance' },
  { id: 502, text: 'I\'m not a singer, but I can make you sing' },
  { id: 503, text: 'I\'m not an artist, but I can draw you closer' },
  { id: 504, text: 'I\'m not a pilot, but I can take you to the clouds' },
  { id: 505, text: 'I\'m not a driver, but I can drive you crazy' },
  { id: 506, text: 'I\'m not a teacher, but I can teach you a lesson' },
  { id: 507, text: 'I\'m not a student, but I can learn from you' },
  { id: 508, text: 'I\'m not a scientist, but I can experiment with you' },
  { id: 509, text: 'I\'m not a lawyer, but I can make a case for us' },
  { id: 510, text: 'I\'m not a judge, but I can sentence you to a lifetime of happiness' },
  { id: 511, text: 'I\'m not a king, but I can be your prince charming' },
  { id: 512, text: 'I\'m not a queen, but I can be your princess' },
  { id: 513, text: 'I\'m not a hero, but I can be your knight in shining armor' },
  { id: 514, text: 'I\'m not a villain, but I can be your bad boy' },
  { id: 515, text: 'I\'m not a saint, but I can be your angel' },
  { id: 516, text: 'I\'m not a devil, but I can be your demon' },
  { id: 517, text: 'I\'m not a god, but I can make you feel like you\'re in heaven' },
  { id: 518, text: 'I\'m not a goddess, but I can make you feel like you\'re in paradise' },
  { id: 519, text: 'I\'m not a star, but I can make your wishes come true' },
  { id: 520, text: 'I\'m not a moon, but I can light up your night' },
  { id: 521, text: 'I\'m not a sun, but I can brighten up your day' },
  { id: 522, text: 'I\'m not a flower, but I can make you bloom' },
  { id: 523, text: 'I\'m not a tree, but I can give you shade' },
  { id: 524, text: 'I\'m not a river, but I can flow with you' },
  { id: 525, text: 'I\'m not an ocean, but I can be your wave' },
  { id: 526, text: 'I\'m not a mountain, but I can be your rock' },
  { id: 527, text: 'I\'m not a bird, but I can make you fly' },
  { id: 528, text: 'I\'m not a bee, but I can be your honey' },
  { id: 529, text: 'I\'m not a cat, but I can be your kitten' },
  { id: 530, text: 'I\'m not a dog, but I can be your puppy' },
  { id: 531, text: 'I\'m not a fish, but I can be your catch' },
  { id: 532, text: 'I\'m not a spider, but I can get you caught in my web' },
  { id: 533, text: 'I\'m not a snake, but I can be your charmer' },
  { id: 534, text: 'I\'m not a bear, but I can be your teddy' },
  { id: 535, text: 'I\'m not a lion, but I can be your king' },
  { id: 536, text: 'I\'m not a tiger, but I can be your tigress' },
  { id: 537, text: 'I\'m not a wolf, but I can be your lone wolf' },
  { id: 538, text: 'I\'m not a fox, but I can be your foxy lady' },
  { id: 539, text: 'I\'m not a horse, but I can be your stallion' },
  { id: 540, text: 'I\'m not a unicorn, but I can make your dreams come true' },
  { id: 541, text: 'I\'m not a dragon, but I can breathe fire into your life' },
  { id: 542, text: 'I\'m not a mermaid, but I can make a splash in your life' },
  { id: 543, text: 'I\'m not a pirate, but I can steal your heart' },
  { id: 544, text: 'I\'m not a ninja, but I can sneak into your heart' },
  { id: 545, text: 'I\'m not a samurai, but I can fight for your love' },
  { id: 546, text: 'I\'m not a cowboy, but I can be your rodeo' },
  { id: 547, text: 'I\'m not a gangster, but I can be your ride or die' },
  { id: 548, text: 'I\'m not a rockstar, but I can be your groupie' },
  { id: 549, text: 'I\'m not a superstar, but I can be your biggest fan' },
  { id: 550, text: 'I\'m not a model, but I can strike a pose for you' },
  { id: 551, text: 'I\'m not an actor, but I can play the role of your lover' },
  { id: 552, text: 'I\'m not an actress, but I can be your leading lady' },
  { id: 553, text: 'I\'m not a director, but I can direct our love story' },
  { id: 554, text: 'I\'m not a producer, but I can produce some magic between us' },
  { id: 555, text: 'I\'m not a screenwriter, but I can write our happy ending' },
  { id: 556, text: 'I\'m not a movie, but I can be your blockbuster' },
  { id: 557, text: 'I\'m not a book, but I can be your favorite chapter' },
  { id: 558, text: 'I\'m not a song, but I can be your favorite tune' },
  { id: 559, text: 'I\'m not a poem, but I can be your rhyme' },
  { id: 560, text: 'I\'m not a painting, but I can be your masterpiece' },
  { id: 561, text: 'I\'m not a sculpture, but I can be your work of art' },
  { id: 562, text: 'I\'m not a museum, but I can be your treasure' },
  { id: 563, text: 'I\'m not a castle, but I can be your fortress' },
  { id: 564, text: 'I\'m not a palace, but I can be your kingdom' },
  { id: 565, text: 'I\'m not a throne, but I can be your royalty' },
  { id: 566, text: 'I\'m not a crown, but I can be your jewel' },
  { id: 567, text: 'I\'m not a diamond, but I can be your precious stone' },
  { id: 568, text: 'I\'m not a pearl, but I can be your gem' },
  { id: 569, text: 'I\'m not a ruby, but I can be your fire' },
  { id: 570, text: 'I\'m not a sapphire, but I can be your blue sky' },
  { id: 571, text: 'I\'m not an emerald, but I can be your green pasture' },
  { id: 572, text: 'I\'m not a gold, but I can be your treasure' },
  { id: 573, text: 'I\'m not a silver, but I can be your shining star' },
  { id: 574, text: 'I\'m not a bronze, but I can be your champion' },
  { id: 575, text: 'I\'m not a winner, but I can be your prize' },
  { id: 576, text: 'I\'m not a loser, but I can be your comfort' },
  { id: 577, text: 'I\'m not a fighter, but I can be your peace' },
  { id: 578, text: 'I\'m not a lover, but I can be your friend' },
  { id: 579, text: 'I\'m not a stranger, but I can be your family' },
  { id: 580, text: 'I\'m not a secret, but I can be your mystery' },
  { id: 581, text: 'I\'m not a puzzle, but I can be your solution' },
  { id: 582, text: 'I\'m not a question, but I can be your answer' },
  { id: 583, text: 'I\'m not a problem, but I can be your solution' },
  { id: 584, text: 'I\'m not a dream, but I can be your reality' },
  { id: 585, text: 'I\'m not a fantasy, but I can be your truth' },
  { id: 586, text: 'I\'m not a lie, but I can be your honesty' },
  { id: 587, text: 'I\'m not a joke, but I can be your happiness' },
  { id: 588, text: 'I\'m not a tear, but I can be your smile' },
  { id: 589, text: 'I\'m not a frown, but I can be your laughter' },
  { id: 590, text: 'I\'m not a storm, but I can be your calm' },
  { id: 591, text: 'I\'m not a fire, but I can be your warmth' },
  { id: 592, text: 'I\'m not an ice, but I can be your cool' },
  { id: 593, text: 'I\'m not a wind, but I can be your breeze' },
  { id: 594, text: 'I\'m not a rain, but I can be your shower' },
  { id: 595, text: 'I\'m not a snow, but I can be your winter wonderland' },
  { id: 596, text: 'I\'m not a spring, but I can be your bloom' },
  { id: 597, text: 'I\'m not a summer, but I can be your sunshine' },
  { id: 598, text: 'I\'m not an autumn, but I can be your fall' },
  { id: 599, text: 'I\'m not a season, but I can be your reason' },
  { id: 600, text: 'I\'m not a day, but I can be your forever' },
];