import type { DrawingStyle } from '../types';

export const DRAWING_STYLES: DrawingStyle[] = [
  // 3D & Render Styles
  { id: 1, name: 'Photorealistic 3D Render' },
  { id: 2, name: 'Low-Poly 3D Model' },
  { id: 3, name: 'High-Gloss Vinyl Toy' },
  { id: 4, name: 'Polished Chrome Finish' },
  { id: 5, name: 'Claymation / Stop-Motion' },
  { id: 6, name: 'Voxel Art (Minecraft-esque)' },
  { id: 7, name: 'Cel-Shaded 3D (Anime Look)' },
  { id: 8, name: 'Holographic / Iridescent' },
  { id: 9, name: 'Neon-Lit 3D Render' },
  { id: 10, name: 'Matte Finish Figurine' },
  { id: 11, name: 'ZBrush Sculpt Detail' },
  { id: 12, name: 'Blender Eevee Render Style' },
  { id: 13, name: 'Unreal Engine 5 Cinematic' },
  { id: 14, name: 'Isometric 3D Diorama' },
  { id: 15, name: 'Clear Resin Cast Toy' },

  // Streetwear & Urban Art
  { id: 16, name: 'Graffiti Tag Style (Wildstyle)' },
  { id: 17, name: 'Bold Sticker Graphic' },
  { id: 18, name: 'Skateboard Deck Art' },
  { id: 19, name: 'Hypebeast Graphic Tee Design' },
  { id: 20, name: 'Wheatpaste Poster Art' },
  { id: 21, name: 'Airbrushed T-Shirt Art' },
  { id: 22, name: 'Stencil Art (Banksy Style)' },
  { id: 23, name: 'Drippy, Slime-Covered Graphic' },
  { id: 24, name: 'Kaws-inspired Character Art' },
  { id: 25, name: 'Murakami Superflat Style' },
  { id: 26, name: 'Obey Giant (Shepard Fairey) Propaganda Style' },
  { id: 27, name: 'Modern Street Art Mural' },
  { id: 28, name: 'Bubble Letter Graffiti' },
  { id: 29, name: 'Sharp Vector Illustration' },
  { id: 30, name: 'Screenprint Poster Look' },

  // Punk & Goth Styles
  { id: 31, name: 'Crust Punk Patchwork Style' },
  { id: 32, name: 'DIY Zine Photocopy Look' },
  { id: 33, name: 'Horror Punk Misfits-style Graphic' },
  { id: 34, name: 'Heavy Metal Album Cover Art' },
  { id: 35, name: 'Blackwork Tattoo Flash' },
  { id: 36, name: 'Gothic Architecture Linework' },
  { id: 37, name: 'Victorian Engraving Style' },
  { id: 38, name: 'Dark Fantasy Illustration (Frank Frazetta-esque)' },
  { id: 39, name: 'Tim Burton-esque Whimsical Goth' },
  { id: 40, name: 'Deathrock Batcave Flyer Art' },
  { id: 41, name: 'Scratched-up Punk Flyer' },
  { id: 42, name: 'Occult Sigil & Woodcut Style' },
  { id: 43, name: 'Corpse Paint Album Art' },
  { id: 44, name: 'Heavy Inked Comic Style (Mike Mignola)' },
  { id: 45, name: 'Post-Punk Joy Division-style Album Art' },

  // Hip Hop Styles
  { id: 46, name: '90s Hip Hop Caricature (Ed Piskor Style)' },
  { id: 47, name: 'Pen & Pixel Bling Album Cover' },
  { id: 48, name: 'Underground Hip Hop Comic Book Art' },
  { id: 49, name: 'Rapper Anime Crossover Style' },
  { id: 50, name: 'Trap Music Glitch Art' },
  { id: 51, name: 'Golden Age Rap Video Fisheye Lens' },
  { id: 52, name: 'Abstract Hip Hop (Stones Throw Records style)' },
  { id: 53, name: 'Soundcloud Rapper Face Tattoo Portrait' },
  { id: 54, name: 'Boom Bap Era Cassette Art' },
  { id: 55, name: 'Modern Rap Music Video 3D Animation' },

  // Other & Hybrid Styles
  { id: 56, name: '8-Bit Pixel Art' },
  { id: 57, name: '16-Bit SNES Style' },
  { id: 58, name: 'Vaporwave Aesthetic' },
  { id: 59, name: 'Synthwave Neon Grid' },
  { id: 60, name: 'Classic American Tattoo (Sailor Jerry)' },
  { id: 61, name: 'Japanese Ukiyo-e Woodblock Print' },
  { id: 62, name: 'Psychedelic 60s Poster Art' },
  { id: 63, name: 'Art Nouveau Intricate Lines' },
  { id: 64, name: 'Art Deco Geometric Style' },
  { id: 65, name: 'Surrealism (Dali-esque)' },
  { id: 66, name: 'Pop Art (Andy Warhol)' },
  { id: 67, name: 'Bauhaus Graphic Design' },
  { id: 68, name: 'Risograph Print Effect' },
  { id: 69, name: 'Halftone Comic Book Shading' },
  { id: 70, name: 'Technical Illustration / Blueprint' },
  { id: 71, name: 'Watercolor Painting' },
  { id: 72, name: 'Oil Painting (Impasto)' },
  { id: 73, name: 'Charcoal Sketch' },
  { id: 74, name: 'Hand-drawn Ink and Crosshatch' },
  { id: 75, name: 'Anime / Manga Style (Modern)' },
  { id: 76, name: '90s Cartoon Network Style' },
  { id: 77, name: 'Rubber Hose Animation (1930s)' },
  { id: 78, name: 'Lowbrow / Pop Surrealism (Mark Ryden style)' },
  { id: 79, name: 'Tribal Tattoo Designs' },
  { id: 80, name: 'Celtic Knotwork' },
  { id: 81, name: 'Stained Glass Window' },
  { id: 82, name: 'Childrens Book Illustration' },
  { id: 83, name: 'Infographic Vector Style' },
  { id: 84, name: 'Biomechanical (H.R. Giger)' },
  { id: 85, name: 'Steampunk Mechanical Drawing' },
  { id: 86, name: 'Cyberpunk 2077 concept art' },
  { id: 87, name: 'Dieselpunk aesthetic' },
  { id: 88, name: 'Solarpunk utopian illustration' },
  { id: 90, name: 'Paper Quilling Art' },
  { id: 91, name: 'Cut Paper collage (Matisse style)' },
  { id: 92, name: 'Double Exposure Photography effect' },
  { id: 93, name: 'Glitchy VHS Screen effect' },
  { id: 94, name: 'Thermal Imaging effect' },
  { id: 95, name: 'X-Ray / Blueprint style' },
  { id: 96, name: 'Cosmic Horror (Lovecraftian)' },
  { id: 97, name: 'Fantasy Map Cartography' },
  { id: 98, name: 'Action Figure Packaging Art' },
  { id: 99, name: 'Brutalist Architecture influence' },
  { id: 100, name: 'Liquid Metal / Chrome effect' },
];
