import type { Trait } from '../types';

export const TRAITS: Trait[] = [
  // --- Material & Texture (31-60) ---
  { id: 31, description: 'Grungy, stained white fabric' },
  { id: 32, description: 'Chipped and cracked porcelain skin texture' },
  { id: 33, description: 'Glistening, wet and fleshy texture' },
  { id: 34, description: 'Thick, gooey black tar coating' },
  { id: 35, description: 'Rough, rotting canvas sackcloth' },
  { id: 36, description: 'Peeling and flaking paint on the body' },
  { id: 37, description: 'Dirty, smeared grease paint texture' },
  { id: 38, description: 'Covered in a sticky, sweet red soda spray' },
  { id: 39, description: 'Old, cracked and scarred leather' },
  { id: 40, description: 'Heavy, worn and ripped denim fabric' },
  { id: 41, description: 'Matted, filthy plush fur' },
  { id: 42, description: 'Exposed, sinewy muscle fiber texture' },
  { id: 43, description: 'Covered in thick, viscous mud' },
  { id: 44, description: 'Rusted and pitted metal plating' },
  { id: 45, description: 'Body appears to be made of stitched-together parts' },
  { id: 46, description: 'Body is made of pulsating, living wires' },
  { id: 47, description: 'Skin is covered in a shimmering, oil-slick iridescence' },
  { id: 48, description: 'Covered in thick, overgrown moss and fungi' },
  { id: 49, description: 'Body appears to be carved from ancient, petrified wood' },
  { id: 50, description: 'Skin has the texture of cracked, dry earth' },
  { id: 51, description: 'Covered in thousands of tiny, writhing insects' },
  { id: 52, description: 'Body is a vessel for a swirling nebula of stars' },
  { id: 53, description: 'Made from melted and re-solidified wax candles' },
  { id: 54, description: 'Covered in brittle, yellowed parchment with arcane symbols' },
  { id: 55, description: 'Skin made of translucent, gelatinous material' },
  { id: 56, description: 'Body is composed of tightly packed, whispering shadows' },
  { id: 57, description: 'Covered in sharp, crystalline growths' },
  { id: 58, description: 'Has a rough, barnacle-encrusted texture' },
  { id: 59, description: 'Skin appears as a glitching, pixelated screen' },
  { id: 60, description: 'Body is wrapped in rusted barbed wire' },

  // --- Face Paint & Markings (61-90) ---
  { id: 61, description: 'Full black and white clown face paint' },
  { id: 62, description: 'Face paint of a grinning skull' },
  { id: 63, description: 'Dark, vertical stripes over the eyes like a jester' },
  { id: 64, description: 'Smeared, chaotic face paint as if applied in a rage' },
  { id: 65, description: 'Minimalist face paint with only black tears and a smile' },
  { id: 66, description: 'Stitched-mouth ghoul face paint design' },
  { id: 67, description: 'Diamond pattern face paint over one eye' },
  { id: 68, description: 'Stylized spiderweb face paint' },
  { id: 69, description: 'Cracked doll-like face paint' },
  { id: 70, description: 'Face paint that mimics exposed muscle and bone' },
  { id: 71, description: 'Neon, glow-in-the-dark face paint' },
  { id: 72, description: 'A single, stark symbol painted on the face' },
  { id: 73, description: 'Face paint that looks like a shattered mirror' },
  { id: 74, description: 'Bio-luminescent tribal markings that pulse with light' },
  { id: 75, description: 'Scarification patterns in complex geometric shapes' },
  { id: 76, description: 'A third eye painted on the forehead, wide open' },
  { id: 77, description: 'Face is a canvas for dripping, graffiti-style tags' },
  { id: 78, description: 'Kintsugi-style markings, as if the face was broken and repaired with gold' },
  { id: 79, description: 'Markings that mimic the constellations of a dead star system' },
  { id: 80, description: 'Face paint of a weeping stone angel' },
  { id: 81, description: 'Elaborate, symmetrical sugar skull (calavera) face paint' },
  { id: 82, description: 'Runes of power are branded onto the cheeks and forehead' },
  { id: 83, description: 'Face paint resembling a glitching television screen with static' },
  { id: 84, description: 'A simple, stark black bar censoring the eyes' },
  { id: 85, description: 'The veins on the face glow with an eerie light from within' },
  { id: 86, description: 'A brand or sigil of a forgotten cult on the face' },
  { id: 87, description: 'Face is painted to look like an anatomical diagram of what is beneath' },
  { id: 88, description: 'War paint made from mud and ash, applied crudely' },

  // --- Head & Features (91-120) ---
  { id: 91, description: 'A wide, maniacal grin with crooked, yellowed teeth' },
  { id: 92, description: 'Mouth stitched shut with thick, crude stitches' },
  { id: 93, description: 'Rotting teeth and visibly decayed gums' },
  { id: 94, description: 'Multiple rows of sharp, needle-like teeth' },
  { id: 95, description: 'A grotesquely long, pointed tongue lolling out' },
  { id: 96, description: 'Hollow, empty eye sockets leaking dark fluid' },
  { id: 97, description: 'A greasy, brightly colored clown wig' },
  { id: 98, description: 'Long, stringy, unkempt black hair' },
  { id: 99, description: 'A dirty, backward-facing baseball cap' },
  { id: 100, description: 'A dark, oversized hood pulled low over the face' },
  { id: 101, description: 'A classic jester\'s hat with drooping, bell-tipped points' },
  { id: 102, description: 'A tattered burlap sack worn as a mask' },
  { id: 103, description: 'Dreadlocks adorned with small, carved bones' },
  { id: 104, description: 'A single, sharp horn protruding from the forehead' },
  { id: 105, description: 'A large, singular eye in the center of the face (cyclops)' },
  { id: 106, description: 'Antlers like a stag, but made of gnarled, dark wood' },
  { id: 107, description: 'The mouth is a vertical slit instead of horizontal' },
  { id: 108, description: 'Gills on the neck that flare and pulse slowly' },
  { id: 109, description: 'The head is a vintage, flickering television screen showing static' },
  { id: 110, description: 'A halo of broken, floating metal shards orbits the head' },
  { id: 111, description: 'Ears are long, pointed, and leathery like a bat' },
  { id: 112, description: 'The head is encased in a cracked deep-sea diver helmet' },
  { id: 113, description: 'A crown of thorns made of rusted barbed wire' },
  { id: 114, description: 'The face is a featureless, smooth mask of skin' },
  { id: 115, description: 'A cage-like muzzle is bolted onto the jaw' },
  { id: 116, description: 'The nose is a skeletal, empty nasal cavity' },
  { id: 117, description: 'Horns like a ram, curled and imposing' },
  { id: 118, description: 'A second, smaller, parasitic face grows from the side of the head' },
  { id: 119, description: 'The head is replaced with a buzzing, leaking beehive' },
  { id: 120, description: 'A black, full-face ski mask' },

  // --- Eyes (CRITICAL) (121-140) ---
  { id: 121, description: 'Intense demonic red glowing eyes' },
  { id: 122, description: 'Mystical purple glowing eyes' },
  { id: 123, description: 'Toxic green glowing eyes' },
  { id: 124, description: 'Fiery orange glowing eyes' },
  { id: 125, description: 'Soulful, electric blue glowing eyes' },
  { id: 126, description: 'Sinister white glowing eyes' },
  { id: 127, description: 'Glowing X-shapes for eyes' },
  { id: 128, description: 'Hypnotic, swirling spiral eyes' },
  { id: 129, description: 'Dead, milky-white cataract eyes' },
  { id: 130, description: 'Black, oil-slick eyes with no pupils or whites' },
  { id: 131, description: 'Eyes are mismatched, one normal and one glowing' },
  { id: 132, description: 'Eyes are multifaceted, like a fly or other insect' },
  { id: 133, description: 'The eyes are old, black and white cartoon-style pie-cut eyes' },
  { id: 134, description: 'Pupils are horizontal slits like a goat' },
  { id: 135, description: 'Eyes are swirling pools of liquid mercury' },
  { id: 136, description: 'Eyes appear as camera lenses, constantly focusing and zooming' },
  { id: 137, description: 'The eyes are dark voids that seem to absorb all light' },
  { id: 138, description: 'Eyes are replaced with glowing, arcane runes' },
  { id: 139, description: 'One eye is a keyhole, promising a hidden secret' },
  { id: 140, description: 'The eyelids are sewn shut with thick thread, yet it can see' },

  // --- Clothing & Attire (141-170) ---
  { id: 141, description: 'A dirty, oversized sports jersey with a strange logo' },
  { id: 142, description: 'A tattered, patchwork clown suit in clashing colors' },
  { id: 143, description: 'A formal ringmaster\'s tailcoat, stained and torn' },
  { id: 144, description: 'A heavy denim jacket covered in crude, hand-drawn patches' },
  { id: 145, description: 'A filthy, hooded sweatshirt with the strings removed' },
  { id: 146, description: 'A straitjacket with long, dangling straps' },
  { id: 147, description: 'A butcher\'s apron, darkly stained' },
  { id: 148, description: 'Baggy, oversized jeans held up by a rope' },
  { id: 149, description: 'Wrapped in heavy, rusted chains and padlocks' },
  { id: 150, description: 'A tattered vest over a bare, heavily scarred chest' },
  { id: 151, description: 'Overalls, one strap undone, covered in grime' },
  { id: 152, description: 'A jester\'s ruffled collar, dirty and frayed' },
  { id: 153, description: 'Wearing a beekeeper\'s suit that is leaking honey and bees' },
  { id: 154, description: 'Dressed in the tattered, hooded robes of a forgotten cult' },
  { id: 155, description: 'Wearing a vintage, stained and cracked hazmat suit' },
  { id: 156, description: 'Body is wrapped in old, yellowed newspaper clippings of tragedies' },
  { id: 157, description: 'Adorned with a heavy cloak made of raven feathers' },
  { id: 158, description: 'Wearing a lab coat stained with unknown, glowing chemicals' },
  { id: 159, description: 'Dressed in a crude patchwork of different animal hides' },
  { id: 160, description: 'Wearing a heavy, antique deep-sea diver\'s suit, covered in barnacles' },
  { id: 161, description: 'A cloak made of living shadows that writhe and twist' },
  { id: 162, description: 'A high-tech, damaged exoskeleton is fused to the body' },
  { id: 163, description: 'Dressed in the uniform of an abandoned asylum orderly' },
  { id: 164, description: 'Wearing a plague doctor\'s long, black coat and beak mask' },
  { id: 165, description: 'A bandolier of strange, glowing potions is slung across the chest' },
  { id: 166, description: 'Wrapped in ancient, ceremonial burial cloths with faded symbols' },
  { id: 167, description: 'Wearing a thick, heavy, stained fisherman\'s sweater and waders' },
  { id: 168, description: 'A long, flowing funeral shroud covers the body' },
  
  // --- Props & Weapons (171-200) ---
  { id: 171, description: 'Wielding a small, sharp hand axe' },
  { id: 172, description: 'Holding a massive, rusty meat cleaver' },
  { id: 173, description: 'Shaking and spraying a bottle of fizzy red soda' },
  { id: 174, description: 'Holding a bunch of black, wilted balloons' },
  { id: 175, description: 'Juggling mismatched, grotesque objects' },
  { id: 176, description: 'Holding a crude, hand-made voodoo doll pierced with pins' },
  { id: 177, description: 'Wielding a giant, cartoonish mallet with nails in it' },
  { id: 178, description: 'Carrying a heavy, leaking sack over one shoulder' },
  { id: 179, description: 'Holding a pair of oversized, rusty shears' },
  { id: 180, description: 'Wielding a microphone stylized like a weapon' },
  { id: 181, description: 'Holding a lit stick of dynamite with a sizzling fuse' },
  { id: 182, description: 'A glowing, arcane symbol on the chest' },
  { id: 183, description: 'Holding a creepy marionette puppet' },
  { id: 184, description: 'Wielding a large, crimson-stained knife' },
  { id: 185, description: 'Holding a sinister jack-in-the-box' },
  { id: 186, description: 'Carrying a gnarled, ancient staff topped with a pulsing crystal' },
  { id: 187, description: 'Wielding a branding iron that is glowing red with heat' },
  { id: 188, description: 'Holding a pair of bone-handled, antique surgical scissors' },
  { id: 189, description: 'Carrying a swinging censer that emits a thick, ominous smoke' },
  { id: 190, description: 'Wielding a heavy, industrial nail gun connected to an air tank' },
  { id: 191, description: 'Holding a music box that plays a discordant, unsettling melody' },
  { id: 192, description: 'Carrying a large, antique key to an unknown, ominous lock' },
  { id: 193, description: 'Wielding a shepherd\'s crook, but it\'s made of polished bone' },
  { id: 194, description: 'Holding a birdcage containing a skeletal, chattering bird' },
  { id: 195, description: 'A long chain and hook, like a meat packer\'s tool, is dragged behind' },
  { id: 196, description: 'Carrying a lantern with a trapped, glowing soul inside' },
  { id: 197, description: 'Wielding an old, rusty bear trap on a chain like a flail' },
  { id: 198, description: 'Holding a specimen jar containing a floating, watching eyeball' },
  { id: 199, description: 'A vintage microphone that constantly screeches with feedback' },
  { id: 200, description: 'Wielding a massive, two-handed sledgehammer with strange runes' },

  // --- Atmosphere & Effects (201-220) ---
  { id: 201, description: 'Surrounded by a shower of cheap, grimy confetti' },
  { id: 202, description: 'Standing in a puddle of thick, dark, viscous liquid' },
  { id: 203, description: 'Set in a grimy, urban back-alley with graffiti' },
  { id: 204, description: 'Set in a dilapidated, abandoned carnival' },
  { id: 205, description: 'Lit by flickering, unreliable fluorescent lights' },
  { id: 206, description: 'A faint, green aura of malevolent energy' },
  { id: 207, description: 'Dripping with a viscous, unidentifiable substance' },
  { id: 208, description: 'A swarm of buzzing flies surrounds the character' },
  { id: 209, description: 'Shadows seem to twist and move in the background' },
  { id: 210, description: 'A thick, unnatural fog swirls around the feet' },
  { id: 211, description: 'The character casts multiple, overlapping shadows that move independently' },
  { id: 212, description: 'Reality seems to glitch and pixelate in a radius around the character' },
  { id: 213, description: 'A faint, discordant music box melody seems to follow them' },
  { id: 214, description: 'Surrounded by a halo of dead, floating insects that orbit their head' },
  { id: 215, description: 'The air around them is visibly cold, frosting nearby surfaces' },
  { id: 216, description: 'A constant, low-frequency, unsettling hum emanates from their body' },
  { id: 217, description: 'The ground cracks and decays where they stand' },
  { id: 218, description: 'Strange, arcane symbols appear and fade in the air around them' },
  { id: 219, description: 'They are lit by the flickering projection of a ghostly, old film' },
  { id: 220, description: 'A shower of black, oily rain falls only on them and sizzles on the ground' },

  // --- Elemental & Organic (221-320) ---
  { id: 221, description: 'Made of molten, glowing lava with a cooling rock crust' },
  { id: 222, description: 'Body is formed from pure, crackling electricity and lightning arcs' },
  { id: 223, description: 'Composed of solid, cracked, deep-blue glacier ice' },
  { id: 224, description: 'Wrapped in thick, thorny ivy and living vines' },
  { id: 225, description: 'Fur is made of dense, aromatic marijuana leaves and buds' },
  { id: 226, description: 'Body is made of cracked, ancient stone with glowing runes' },
  { id: 227, description: 'Wreathed in an aura of black, sooty smoke and embers' },
  { id: 228, description: 'Made of churning, murky swamp water and algae' },
  { id: 229, description: 'A being of living soundwaves, visibly distorting the air' },
  { id: 230, description: 'Covered in a symbiotic layer of glowing, psychedelic mushrooms' },
  { id: 231, description: 'Skin is charred, smoldering charcoal with embers glowing within' },
  { id: 232, description: 'Body is a walking void, a hole in reality revealing a starfield within' },
  { id: 233, description: 'Composed of tightly packed, decaying autumn leaves' },
  { id: 234, description: 'Skin has the texture of rough, crumbling sandstone' },
  { id: 235, description: 'Made from solidified, rainbow-hued light' },
  { id: 236, description: 'A being of pure toxicity, leaking green sludge and acidic ooze' },
  { id: 237, description: 'Guts are a tangle of living roots, visible through gaps in the body' },
  { id: 238, description: 'Body is a vessel for a miniature, raging thunderstorm' },
  { id: 239, description: 'Made of swirling, spectral mist and fog' },
  { id: 240, description: 'Covered in sharp, obsidian shards' },
  { id: 241, description: 'Flowers of a poisonous variety bloom from its wounds' },
  { id: 242, description: 'Body is made of liquid, flowing mercury' },
  { id: 243, description: 'Composed of raw, unstable magical energy' },
  { id: 244, description: 'A walking thicket of dead, thorny branches' },
  { id: 245, description: 'Covered in a layer of frost and sharp icicles' },
  { id: 246, description: 'Skin is iridescent, like bismuth crystal' },
  { id: 247, description: 'Veins glow with internal magma' },
  { id: 248, description: 'Body is a hive for swarming, venomous hornets' },
  { id: 249, description: 'Formed from crystallized, fossilized bone and amber' },
  { id: 250, description: 'Made of writhing, semi-solid tendrils of shadow' },
  { id: 251, description: 'Surrounded by a powerful, gusting whirlwind of dust and debris' },
  { id: 252, description: 'Skin is tough, protective tree bark' },
  { id: 253, description: 'Body is a prism, refracting light into chaotic, colorful patterns' },
  { id: 254, description: 'Covered in a patina of rusted, verdigris-covered copper' },
  { id: 255, description: 'Body is composed of packed, damp grave soil and worms' },
  { id: 256, description: 'Made of shimmering, ethereal ectoplasm' },
  { id: 257, description: 'A glitching hologram composed of static and corrupted light' },
  { id: 258, description: 'Body is a lode of raw, unrefined gold ore' },
  { id: 259, description: 'Covered in bioluminescent moss and parasitic fungi' },
  { id: 260, description: 'Composed of swirling, colored sand like a sand-art bottle' },
  { id: 261, description: 'Skin is a living map of glowing constellations' },
  { id: 262, description: 'Body is a golem of wet clay and river stones' },
  { id: 263, description: 'Fur is composed of flickering, ethereal blue and white flames' },
  { id: 264, description: 'Made from jagged, slate-like plates of rock' },
  { id: 265, description: 'Body made of superheated, shimmering plasma' },
  { id: 266, description: 'Constantly dripping with viscous, black toxic ooze' },
  { id: 267, description: 'Body is covered in pulsating, corrupted energy crystals' },
  { id: 268, description: 'Made from tightly woven, living plant fibers' },
  { id: 269, description: 'A being made of pure, solidified sound' },
  { id: 270, description: 'Body is a geode, cracked open to reveal a sparkling crystalline interior' },
  { id: 271, description: 'Made of swirling cosmic dust and nebulae' },
  { id: 272, description: 'Body is a living coral reef with small, symbiotic fish' },
  { id: 273, description: 'Composed of shifting, wind-blown desert sands' },
  { id: 274, description: 'A being of pure, solidified and glowing moonlight' },
  { id: 275, description: 'Skin is iridescent, like a soap bubble\'s surface' },
  { id: 276, description: 'Formed from volcanic ash and sharp obsidian glass' },
  { id: 277, description: 'Body is a column of raging, sentient fire' },
  { id: 278, description: 'Made of tangled, sentient kelp and deep-sea seaweed' },
  { id: 279, description: 'A walking geode with a glittering, crystalline interior exposed' },
  { id: 280, description: 'Wreathed in an aura of pure, flaring solar energy' },
  { id: 281, description: 'Composed of petrified, fossilized ancient wood' },
  { id: 282, description: 'Body is a living, shifting aurora borealis' },
  { id: 283, description: 'Made from solidified, humming soundwaves' },
  { id: 284, description: 'Covered in a layer of magnetic, shifting ferrofluid' },
  { id: 285, description: 'Formed from radioactive, glowing green ooze' },
  { id: 286, description: 'A being of pure shadow and light-absorbing anti-light' },
  { id: 287, description: 'Skin is made of polished, smooth river stones' },
  { id: 288, description: 'Body is a cohesive swarm of glowing fireflies' },
  { id: 289, description: 'Composed of prismatic, light-refracting crystal' },
  { id: 290, description: 'Made of raw, uncut, and unrefined diamond' },
  { id: 291, description: 'A living whirlwind of razor-sharp autumn leaves' },
  { id: 292, description: 'Body is a vessel for a miniature, gravity-bending black hole' },
  { id: 293, description: 'Skin has the texture of cooled, hexagonal basalt rock columns' },
  { id: 294, description: 'Wreathed in an aura of pure, bone-chilling cold' },
  { id: 295, description: 'Made from living, pulsating fungal mycelium network' },
  { id: 296, description: 'Composed of solidified, insect-trapping tree amber' },
  { id: 297, description: 'Body is a flowing river of liquid nitrogen' },
  { id: 298, description: 'A being of pure, concentrated starlight' },
  { id: 299, description: 'Skin is covered in a layer of shimmering, wet clay' },
  { id: 300, description: 'Made of ethereal, wispy and semi-transparent ectoplasm' },
  { id: 301, description: 'Body is a living patch of bioluminescent deep-sea algae' },
  { id: 302, description: 'Composed of raw, chaotic, and sparking elemental magic' },
  { id: 303, description: 'A walking earthquake, ground cracking with each step' },
  { id: 304, description: 'Made from molten, iridescent, and flowing glass' },
  { id: 305, description: 'Body is a living rainbow, constantly shifting colors' },
  { id: 306, description: 'Wreathed in an aura of pure, life-draining negative energy' },
  { id: 307, description: 'Skin is covered in a layer of fine, sparkling salt crystals' },
  { id: 308, description: 'Composed of pure, solidified methane ice from a distant moon' },
  { id: 309, description: 'Body is a living swarm of metallic, clockwork insects' },
  { id: 310, description: 'Made from tangled, sparking, and arcing power lines' },
  { id: 311, description: 'A being of pure, crystallized honey, dripping slowly' },
  { id: 312, description: 'Skin is made of overlapping, iridescent fish scales' },
  { id: 313, description: 'Body is a living, breathing, shifting sand dune' },
  { id: 314, description: 'Composed of pure, solidified emotion, like rage or sorrow' },
  { id: 315, description: 'A walking ecosystem of miniature, symbiotic plants' },
  { id: 316, description: 'Made from the compressed, inked pages of forgotten books' },
  { id: 317, description: 'Body is a living, breathing, tangled ball of yarn' },
  { id: 318, description: 'Composed of pure, solidified, and shimmering mother-of-pearl' },
  { id: 319, description: 'Wreathed in an aura of disorienting, psychic static' },
  { id: 320, description: 'Made from living, breathing, and musically chiming stained glass' },

  // --- Material & Texture II (321-370) ---
  { id: 321, description: 'Covered in slick, wet latex or rubber' },
  { id: 322, description: 'Skin is made of rough, unfinished concrete' },
  { id: 323, description: 'Has a texture of old, peeling wallpaper' },
  { id: 324, description: 'Body is made of brittle, dried snakeskin' },
  { id: 325, description: 'Covered in a layer of fine, black velvet flocking' },
  { id: 326, description: 'Skin has the texture of a porous, natural sea sponge' },
  { id: 327, description: 'Made from melted and warped vinyl records' },
  { id: 328, description: 'Covered in a patchwork of old, faded persian rugs' },
  { id: 329, description: 'Body is a mass of tangled, multicolored wires and cables' },
  { id: 330, description: 'Skin has the texture of rough, industrial sandpaper' },
  { id: 331, description: 'Covered in a layer of smooth, polished marble' },
  { id: 332, description: 'Body is made of iridescent, holographic plastic foil' },
  { id: 333, description: 'Has the texture of a fuzzy, static-filled television screen' },
  { id: 334, description: 'Made from tightly woven carbon fiber' },
  { id: 335, description: 'Covered in a layer of sticky, fibrous candy floss' },
  { id: 336, description: 'Skin has the texture of cracked, glazed ceramic' },
  { id: 337, description: 'Body is composed of thousands of tiny, reflective mirror shards' },
  { id: 338, description: 'Made from old, yellowed insulating foam' },
  { id: 339, description: 'Covered in a layer of soft, supple suede' },
  { id: 340, description: 'Skin has the texture of a bumpy, reptilian hide' },
  { id: 341, description: 'Body is made from recycled, shredded plastic' },
  { id: 342, description: 'Has the texture of a plush, high-pile shag carpet' },
  { id: 343, description: 'Covered in a layer of greasy, industrial machine oil' },
  { id: 344, description: 'Skin is made of smooth, anodized aluminum' },
  { id: 345, description: 'Body is a mass of melted, dripping crayons' },
  { id: 346, description: 'Has the texture of a soft, squishy memory foam' },
  { id: 347, description: 'Covered in a layer of iridescent, shimmering glitter' },
  { id: 348, description: 'Skin is made of translucent, colored acrylic resin' },
  { id: 349, description: 'Body is a tangled mess of old audio cassette tape' },
  { id: 350, description: 'Made from layered, corrugated cardboard' },
  { id: 351, description: 'Covered in a layer of soft, synthetic astroturf' },
  { id: 352, description: 'Skin has the texture of a rough, fibrous coconut husk' },
  { id: 353, description: 'Body is made of tightly packed, brightly colored feathers' },
  { id: 354, description: 'Has the texture of bumpy, cushioned bubble wrap' },
  { id: 355, description: 'Covered in a layer of smooth, cool-to-the-touch porcelain' },
  { id: 356, description: 'Skin is made of rough, scarred, and weathered wood planks' },
  { id: 357, description: 'Body is composed of antique, brass clockwork gears' },
  { id: 358, description: 'Made from layers of translucent, colored cellophane' },
  { id: 359, description: 'Covered in a layer of soft, pliable modeling clay' },
  { id: 360, description: 'Skin has the texture of a prickly, spiny cactus' },
  { id: 361, description: 'Body is a jumble of discarded, vintage electronic components' },
  { id: 362, description: 'Has the texture of a rough, woven burlap sack' },
  { id: 363, description: 'Covered in a layer of smooth, reflective chrome' },
  { id: 364, description: 'Skin is made of soft, fuzzy felt fabric' },
  { id: 365, description: 'Body is a mosaic of broken, colored sea glass' },
  { id: 366, description: 'Made from tightly coiled, rusty springs and coils' },
  { id: 367, description: 'Covered in a layer of slick, slimy snail trails' },
  { id: 368, description: 'Skin has the texture of a worn-out, bristly scrub brush' },
  { id: 369, description: 'Body is a mass of tangled, glowing fiber optic strands' },
  { id: 370, description: 'Has the texture of rough, volcanic pumice stone' },

  // --- Streetwear Attire (371-380) ---
  { id: 371, description: 'A black, full-face ski mask obscuring all features' },
  { id: 372, description: 'A plain, slightly worn black tee-shirt' },
  { id: 373, description: 'All-black work overalls with one shoulder strap undone and hanging loose' },
  { id: 374, description: 'Rugged, black Nike-style combat boots with thick soles' },
  { id: 375, description: 'A heavy silver chain necklace with a menacing bat emblem pendant' },
  { id: 376, description: 'A folded green bandana tied around one shoulder' },
  { id: 377, description: 'Classic red and white DC-style chunky skater shoes' },
  { id: 378, description: 'Extremely baggy, faded grey denim jeans' },
  { id: 379, description: 'A streetwear t-shirt covered in random, colorful paint splatters' },
  { id: 380, description: 'A simple, black beanie pulled down low' },
];